import gust from './assets/earring/gust.png'
import order from './assets/earring/order.png'

import chasm from './assets/necklace/chasm.png'
import lava from './assets/necklace/lava.png'
import lifeblood from './assets/necklace/lifeblood.png'

import gale from './assets/ring/gale.png'
import glacial from './assets/ring/glacial.png'
import sapling from './assets/ring/sapling.png'
import solar from './assets/ring/solar.png'

import assault from './assets/class/assault.png'
import tank from './assets/class/tank.png'
import healer from './assets/class/healer.png'
import mage from './assets/class/mage.png'
import ranger from './assets/class/ranger.png'

import amy from './assets/heroes/amy.png'
import arme from './assets/heroes/arme.png'
import arsad from './assets/heroes/arsad.png'
import asin from './assets/heroes/asin.png'
import dio from './assets/heroes/dio.png'
import edel from './assets/heroes/edel.png'
import elesis from './assets/heroes/elesis.png'
import europa from './assets/heroes/europa.png'
import gaian from './assets/heroes/gaian.png'
import grandiel from './assets/heroes/grandiel.png'
import hwarin from './assets/heroes/hwarin.png'
import io from './assets/heroes/io.png'
import jin from './assets/heroes/jin.png'
import kanavan from './assets/heroes/kanavan.png'
import lass from './assets/heroes/lass.png'
import ley from './assets/heroes/ley.png'
import lime from './assets/heroes/lime.png'
import lire from './assets/heroes/lire.png'
import mari from './assets/heroes/mari.png'
import nelia from './assets/heroes/nelia.png'
import rin from './assets/heroes/rin.png'
import ronan from './assets/heroes/ronan.png'
import rufus from './assets/heroes/rufus.png'
import ryan from './assets/heroes/ryan.png'
import serdin from './assets/heroes/serdin.png'
import sieghart from './assets/heroes/sieghart.png'
import tia from './assets/heroes/tia.png'
import veigas from './assets/heroes/veigas.png'
import werner from './assets/heroes/werner.png'
import zero from './assets/heroes/zero.png'

import tia2 from './assets/landinghero/tia2.png'
import hwarin2 from './assets/landinghero/hwarin2.png'
import europa2 from './assets/landinghero/europa2.png'
import io2 from './assets/landinghero/io2.png'
import zero2 from './assets/landinghero/zero2.png'
import werner2 from './assets/landinghero/werner2.png'
import veigas2 from './assets/landinghero/veigas2.png'
import sieghart2 from './assets/landinghero/sieghart2.png'
import serdin2 from './assets/landinghero/serdin2.png'
import ryan2 from './assets/landinghero/ryan2.png'
import elesis2 from './assets/landinghero/elesis2.png'
import lire2 from './assets/landinghero/lire2.png'
import arme2 from './assets/landinghero/arme2.png'
import lass2 from './assets/landinghero/lass2.png'
import ronan2 from './assets/landinghero/ronan2.png'
import amy2 from './assets/landinghero/amy2.png'
import jin2 from './assets/landinghero/jin2.png'
import mari2 from './assets/landinghero/mari2.png'
import dio2 from './assets/landinghero/dio2.png'
import ley2 from './assets/landinghero/ley2.png'
import rufus2 from './assets/landinghero/rufus2.png'
import rin2 from './assets/landinghero/rin2.png'
import asin2 from './assets/landinghero/asin2.png'
import lime2 from './assets/landinghero/lime2.png'
import edel2 from './assets/landinghero/edel2.png'
import kanavan2 from './assets/landinghero/kanavan2.png'
import grandiel2 from './assets/landinghero/grandiel2.png'
import nelia2 from './assets/landinghero/nelia2.png'
import gaian2 from './assets/landinghero/gaian2.png'
import arsad2 from './assets/landinghero/arsad2.png'

import sr from './assets/diamond/sr.png'

import tiav from './assets/profiles/tiav.png'
import elesisv from './assets/profiles/elesisv.png'
import lirev from './assets/profiles/lirev.png'
import armev from './assets/profiles/armev.png'
import lassv from './assets/profiles/lassv.png'
import ryanv from './assets/profiles/ryanv.png'
import ronanv from './assets/profiles/ronanv.png'
import amyv from './assets/profiles/amyv.png'
import jinv from './assets/profiles/jinv.png'
import sieghartv from './assets/profiles/sieghartv.png'
import mariv from './assets/profiles/mariv.png'
import diov from './assets/profiles/diov.png'
import zerov from './assets/profiles/zerov.png'
import leyv from './assets/profiles/leyv.png'
import rufusv from './assets/profiles/rufusv.png'
import rinv from './assets/profiles/rinv.png'
import asinv from './assets/profiles/asinv.png'
import limev from './assets/profiles/limev.png'
import edelv from './assets/profiles/edelv.png'
import veigasv from './assets/profiles/veigasv.png'
import serdinv from './assets/profiles/serdinv.png'
import kanavanv from './assets/profiles/kanavanv.png'
import wernerv from './assets/profiles/wernerv.png'
import grandielv from './assets/profiles/grandielv.png'
import neliav from './assets/profiles/neliav.png'
import iov from './assets/profiles/iov.png'
import hwarinv from './assets/profiles/hwarinv.png'
import europav from './assets/profiles/europav.png'
import gaianv from './assets/profiles/gaianv.png'
import arsadv from './assets/profiles/arsadv.png'

import pion from './assets/pets/pion.png'
import almong from './assets/pets/almong.png'
import crocell from './assets/pets/crocell.png'
import dangel from './assets/pets/dangel.png'
import dia from './assets/pets/dia.png'
import elion from './assets/pets/elion.png'
import gnar from './assets/pets/gnar.png'
import goldporkcard from './assets/pets/goldporkcard.png'
import holy from './assets/pets/holy.png'
import hoya from './assets/pets/hoya.png'
import howl from './assets/pets/howl.png'
import hunt from './assets/pets/hunt.png'
import hwarang from './assets/pets/hwarang.png'
import luce from './assets/pets/luce.png'
import luri from './assets/pets/luri.png'
import manbo from './assets/pets/manbo.png'
import marifa from './assets/pets/marifa.png'
import montero from './assets/pets/montero.png'
import muse from './assets/pets/muse.png'
import nelion from './assets/pets/nelion.png'
import niah from './assets/pets/niah.png'
import raul from './assets/pets/raul.png'
import reruby from './assets/pets/reruby.png'
import res from './assets/pets/res.png'
import rupe from './assets/pets/rupe.png'
import sally from './assets/pets/sally.png'
import sebastian from './assets/pets/sebastian.png'
import shin from './assets/pets/shin.png'
import tcon from './assets/pets/tcon.png'
import temphy from './assets/pets/temphy.png'
import zeta from './assets/pets/zeta.png'

import acceleration from './assets/partyskill/acceleration.jpg'
import resurrect from './assets/partyskill/resurrect.jpg'
import stimulation from './assets/partyskill/stimulation.jpg'

import wbelesis from './assets/worldboss/wbelesis.png'
//import wbkanavan from './assets/worldboss/wbkanavan.png'
//import wbeuropa from './assets/worldboss/wbeuropa.png'
//import wbtia from './assets/worldboss/wbtia.png'
import wblire from './assets/worldboss/wblire.png'
import wbserdin from './assets/worldboss/wbserdin.png'
//import wbwerner from './assets/worldboss/wbwerner.png'
import wbedel from './assets/worldboss/wbedel.png'
import wbarme from './assets/worldboss/wbarme.png'
import wbamy from './assets/worldboss/wbamy.png'
import wbgrandiel from './assets/worldboss/wbgrandiel.png'
import wbmari from './assets/worldboss/wbmari.png'
import wbnelia from './assets/worldboss/wbnelia.png'
import wbley from './assets/worldboss/wbley.png'
import wbrufus from './assets/worldboss/wbrufus.png'
import wblass from './assets/worldboss/wblass.png'
import wbzero from './assets/worldboss/wbzero.png'
import wbryan from './assets/worldboss/wbryan.png'
import wbrin from './assets/worldboss/wbrin.png'
import wbasin from './assets/worldboss/wbasin.png'
import wblime from './assets/worldboss/wblime.png'
import wbjin from './assets/worldboss/wbjin.png'
import wbronan from './assets/worldboss/wbronan.png'
import wbveigas from './assets/worldboss/wbveigas.png'
//import wbdio from './assets/worldboss/wbdio.png'
import wbio from './assets/worldboss/wbio.png'
//import wbsieghart from './assets/worldboss/wbsieghart.png'
import wbhwarin from './assets/worldboss/wbhwarin.png'

import grandielchaser from './assets/skills/grandielchaser.png'
import tiachaser from './assets/skills/tiachaser.png'
import tias2 from './assets/skills/tias2.png'
import tiapassive from './assets/skills/tiapassive.png'
import asinchaser from './assets/skills/asinchaser.png'
import europachaser from './assets/skills/europachaser.png'
import europapassive from './assets/skills/europapassive.png'
import europas1 from './assets/skills/europas1.png'
import limechaser from './assets/skills/limechaser.png'
import neliachaser from './assets/skills/neliachaser.png'
import serdinchaser from './assets/skills/serdinchaser.png'
import veigaschaser from './assets/skills/veigaschaser.png'
import wernerchaser from './assets/skills/wernerchaser.png'
import diochaser from './assets/skills/diochaser.png'
import asinpass from './assets/skills/asinpass.png'
import rufuspass from './assets/skills/rufuspass.png'
import ryans2 from './assets/skills/ryans2.png'
import lasspass from './assets/skills/lasspass.png'
import amychaser from './assets/skills/amychaser.png'
import amypass from './assets/skills/amypass.png'
import amys1 from './assets/skills/amys1.png'
import armechaser from './assets/skills/armechaser.png'
import armepass from './assets/skills/armepass.png'
import armes1 from './assets/skills/armes1.png'
import asins2 from './assets/skills/asins2.png'
import diopass from './assets/skills/diopass.png'
import dios1 from './assets/skills/dios1.png'
import edelpass from './assets/skills/edelpass.png'
import edels2 from './assets/skills/edels2.png'
import edelchaser from './assets/skills/edelchaser.png'
import elesischaser from './assets/skills/elesischaser.png'
import elesispass from './assets/skills/elesispass.png'
import elesiss2 from './assets/skills/elesiss2.png'
import grandiels1 from './assets/skills/grandiels1.png'
import grandiels2 from './assets/skills/grandiels2.png'
import hwarins2 from './assets/skills/hwarins2.png'
import hwarinpass from './assets/skills/hwarinpass.png'
import hwarinchaser from './assets/skills/hwarinchaser.png'
import iochaser from './assets/skills/iochaser.png'
import iopass from './assets/skills/iopass.png'
import ios1 from './assets/skills/ios1.png'
import jins1 from './assets/skills/jins1.png'
import jins2 from './assets/skills/jins2.png'
import jinchaser from './assets/skills/jinchaser.png'
import kanavans1 from './assets/skills/kanavans1.png'
import kanavans2 from './assets/skills/kanavans2.png'
import kanavanchaser from './assets/skills/kanavanchaser.png'
import lasschaser from './assets/skills/lasschaser.png'
import lasss2 from './assets/skills/lasss2.png'
import leychaser from './assets/skills/leychaser.png'
import leypass from './assets/skills/leypass.png'
import leys2 from './assets/skills/leys2.png'
import limepass from './assets/skills/limepass.png'
import limes2 from './assets/skills/limes2.png'
import lirechaser from './assets/skills/lirechaser.png'
import lirepass from './assets/skills/lirepass.png'
import lires2 from './assets/skills/lires2.png'
import marichaser from './assets/skills/marichaser.png'
import maripass from './assets/skills/maripass.png'
import maris1 from './assets/skills/maris1.png'
import neliapass from './assets/skills/neliapass.png'
import nelias2 from './assets/skills/nelias2.png'
import rinchaser from './assets/skills/rinchaser.png'
import rins1 from './assets/skills/rins1.png'
import rins2 from './assets/skills/rins2.png'
import ronanchaser from './assets/skills/ronanchaser.png'
import ronanpass from './assets/skills/ronanpass.png'
import ronans2 from './assets/skills/ronans2.png'
import rufuss1 from './assets/skills/rufuss1.png'
import rufuschaser from './assets/skills/rufuschaser.png'
import ryanchaser from './assets/skills/ryanchaser.png'
import ryans1 from './assets/skills/ryans1.png'
import serdins1 from './assets/skills/serdins1.png'
import serdins2 from './assets/skills/serdins2.png'
import sieghartchaser from './assets/skills/sieghartchaser.png'
import sieghartpass from './assets/skills/sieghartpass.png'
import siegharts1 from './assets/skills/siegharts1.png'
import veigaspass from './assets/skills/veigaspass.png'
import veigass1 from './assets/skills/veigass1.png'
import wernerpass from './assets/skills/wernerpass.png'
import werners2 from './assets/skills/werners2.png'
import zeropass from './assets/skills/zeropass.png'
import zeros1 from './assets/skills/zeros1.png'
import zerochaser from './assets/skills/zerochaser.png'

import badi from './assets/traits/badi.png'
import badr from './assets/traits/badr.png'
import basi from './assets/traits/basi.png'
import cdr from './assets/traits/cdr.png'
import crit from './assets/traits/crit.png'
import csr from './assets/traits/csr.png'
import sadi from './assets/traits/sadi.png'
import sadr from './assets/traits/sadr.png'

import assaulta from './assets/artifacts/assaulta.png'
import healera from './assets/artifacts/healera.png'
import magea from './assets/artifacts/magea.png'
import rangera from './assets/artifacts/rangera.png'
import tanka from './assets/artifacts/tanka.png'

import breathoflife from './assets/chaser/breathoflife.jpg'
import divineprotection from './assets/chaser/divineprotection.jpg'
import elevatedpower from './assets/chaser/elevatedpower.jpg'
import fate from './assets/chaser/fate.jpg'
import helper from './assets/chaser/helper.jpg'
import impulse from './assets/chaser/impulse.jpg'
import invisiblehand from './assets/chaser/invisiblehand.jpg'
import longlife from './assets/chaser/longlife.jpg'
import persistentexecutioner from './assets/chaser/persistentexecutioner.jpg'
import prayerofblessing from './assets/chaser/prayerofblessing.jpg'
import pureluck from './assets/chaser/pureluck.jpg'

import amyfluffy from './assets/fluffy/amyfluffy.png'
import armefluffy from './assets/fluffy/armefluffy.png'
import arsadfluffy from './assets/fluffy/arsadfluffy.png'
import asinfluffy from './assets/fluffy/asinfluffy.png'
import diofluffy from './assets/fluffy/diofluffy.png'
import edelfluffy from './assets/fluffy/edelfluffy.png'
import elesisfluffy from './assets/fluffy/elesisfluffy.png'
import gaianfluffy from './assets/fluffy/gaianfluffy.png'
import grandielfluffy from './assets/fluffy/grandielfluffy.png'
import iofluffy from './assets/fluffy/iofluffy.png'
import jinfluffy from './assets/fluffy/jinfluffy.png'
import kanavanfluffy from './assets/fluffy/kanavanfluffy.png'
import lassfluffy from './assets/fluffy/lassfluffy.png'
import leyfluffy from './assets/fluffy/leyfluffy.png'
import limefluffy from './assets/fluffy/limefluffy.png'
import lirefluffy from './assets/fluffy/lirefluffy.png'
import marifluffy from './assets/fluffy/marifluffy.png'
import neliafluffy from './assets/fluffy/neliafluffy.png'
import rinfluffy from './assets/fluffy/rinfluffy.png'
import ronanfluffy from './assets/fluffy/ronanfluffy.png'
import rufusfluffy from './assets/fluffy/rufusfluffy.png'
import ryanfluffy from './assets/fluffy/ryanfluffy.png'
import serdinfluffy from './assets/fluffy/serdinfluffy.png'
import sieghartfluffy from './assets/fluffy/sieghartfluffy.png'
import veigasfluffy from './assets/fluffy/veigasfluffy.png'
import wernerfluffy from './assets/fluffy/wernerfluffy.png'
import zerofluffy from './assets/fluffy/zerofluffy.png'

import darkagios from './assets/dchasm/darkagios.png'
import darkaltair from './assets/dchasm/darkaltair.png'
import darkbalzac from './assets/dchasm/darkbalzac.png'
import darkbelial from './assets/dchasm/darkbelial.png'
import darkbf from './assets/dchasm/darkbf.png'
import darkbriel from './assets/dchasm/darkbriel.png'
import darkcaptainboar from './assets/dchasm/darkcaptainboar.png'
import darkcharon from './assets/dchasm/darkcharon.png'
import darkdrmolly from './assets/dchasm/darkdrmolly.png'
import darkdullahan from './assets/dchasm/darkdullahan.png'
import darkfavian from './assets/dchasm/darkfavian.png'
import darkfennel from './assets/dchasm/darkfennel.png'
import darkfermat from './assets/dchasm/darkfermat.png'
import darkflaune from './assets/dchasm/darkflaune.png'
import darkhaggler from './assets/dchasm/darkhaggler.png'
import darkhanout from './assets/dchasm/darkhanout.png'
import darkkarp from './assets/dchasm/darkkarp.png'
import darkkyle from './assets/dchasm/darkkyle.png'
import darkmarjoram from './assets/dchasm/darkmarjoram.png'
import darknephilim from './assets/dchasm/darknephilim.png'
import darkposeidon from './assets/dchasm/darkposeidon.png'
import darkrasel from './assets/dchasm/darkrasel.png'
import darktacoel from './assets/dchasm/darktacoel.png'
import darkvega from './assets/dchasm/darkvega.png'

import bossfight from './assets/diamond/bossfight.png'
import brawl from './assets/diamond/brawl.png'
import elite from './assets/diamond/elite.png'
import relay from './assets/diamond/relay.png'

import crazyenvoy from './assets/diamond/crazyenvoy.png'

import swayingambition from './assets/diamond/swayingambition.png'
import illusionofmemory from './assets/diamond/illusionofmemory.png'
import towermanager from './assets/diamond/towermanager.png'
import rulersrights from './assets/diamond/rulersrights.png'
import resurrectionceremony from './assets/diamond/resurrectionceremony.png'
import castedshadow from './assets/diamond/castedshadow.png'
import crazyenvoy2 from './assets/diamond/crazyenvoy2.png'

//import a1 from './assets/diamond/a1.png'
//import a2 from './assets/diamond/a2.png'
//import a3 from './assets/diamond/a3.png'
//import a4 from './assets/diamond/a4.png'
//import a5 from './assets/diamond/a5.png'
//import a6 from './assets/diamond/a6.png'
//import t1 from './assets/diamond/t1.png'
//import t2 from './assets/diamond/t2.png'
import t3 from './assets/diamond/t3.png'
//import t4 from './assets/diamond/t4.png'
//import t5 from './assets/diamond/t5.png'
import t6 from './assets/diamond/t6.png'
//import star6 from './assets/diamond/star6.png'

//export const nullToNone = word => null ? word : 'none'

export const displayUpperCase = word => {
  if (word === 'bov') {
    return 'B.O.V.'
  }
  if (word === 'aot') {
    return 'A.O.T.'
  }
  return word
}

export const grandChaseData = [
  {
    stage: '1-3',
    boss: ['tank'],
    mats: ['enchants'],
    evos: null,
    sUnit: null,
  },
  {
    stage: '1-6',
    boss: ['healer'],
    mats: ['enchants'],
    evos: null,
    sUnit: null,
  },
  {
    stage: '1-9',
    boss: ['mage'],
    mats: ['enchants'],
    evos: null,
    sUnit: null,
  },
  {
    stage: '2-3',
    boss: ['mage'],
    mats: ['enchants', 'bov'],
    evos: null,
    sUnit: null,
  },
  {
    stage: '2-6',
    boss: ['mage'],
    mats: ['enchants', 'bov'],
    evos: null,
    sUnit: null,
  },
  {
    stage: '2-9',
    boss: ['ranger'],
    mats: ['enchants', 'bov'],
    evos: null,
    sUnit: null,
  },
  {
    stage: '3-3',
    boss: ['mage'],
    mats: ['enchants', 'bov'],
    evos: ['healer'],
    sUnit: null,
  },
  {
    stage: '3-6',
    boss: ['mage'],
    mats: ['enchants', 'bov'],
    evos: ['tank'],
    sUnit: null,
  },
  {
    stage: '3-9',
    boss: ['tank'],
    mats: ['enchants', 'bov'],
    evos: ['assault'],
    sUnit: null,
  },
  {
    stage: '4-3',
    boss: ['tank'],
    mats: ['enchants', 'bov'],
    evos: ['mage'],
    sUnit: null,
  },
  {
    stage: '4-6',
    boss: ['mage'],
    mats: ['enchants', 'bov'],
    evos: ['ranger'],
    sUnit: null,
  },
  {
    stage: '4-9',
    boss: ['assault'],
    mats: ['enchants', 'bov'],
    evos: ['healer'],
    sUnit: null,
  },
  {
    stage: '5-3',
    boss: ['assault'],
    mats: ['enchants', 'bov'],
    evos: ['tank'],
    sUnit: null,
  },
  {
    stage: '5-6',
    boss: ['ranger'],
    mats: ['enchants', 'bov'],
    evos: ['assault'],
    sUnit: null,
  },
  {
    stage: '5-9',
    boss: ['mage'],
    mats: ['enchants', 'bov'],
    evos: ['mage'],
    sUnit: null,
  },
  {
    stage: '6-3',
    boss: ['mage'],
    mats: ['enchants', 'bov'],
    evos: ['ranger'],
    sUnit: null,
  },
  {
    stage: '6-6',
    boss: ['ranger'],
    mats: ['enchants'],
    evos: ['tank'],
    sUnit: ['tank'],
  },
  {
    stage: '6-9',
    boss: ['mage'],
    mats: ['enchants'],
    evos: ['mage'],
    sUnit: ['mage'],
  },
  {
    stage: '7-3',
    boss: ['assault'],
    mats: ['enchants'],
    evos: ['ranger'],
    sUnit: ['ranger'],
  },
  {
    stage: '7-6',
    boss: ['mage'],
    mats: ['enchants'],
    evos: ['healer'],
    sUnit: ['healer'],
  },
  {
    stage: '7-9',
    boss: ['assault'],
    mats: ['enchants'],
    evos: ['assault'],
    sUnit: ['assault'],
  },
  {
    stage: '8-3',
    boss: ['assault'],
    mats: ['enchants', 'bov', 'runes', 'aot'],
    evos: ['healer'],
    sUnit: null,
  },
  {
    stage: '8-6',
    boss: ['ranger'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['tank'],
    sUnit: ['tank'],
  },
  {
    stage: '8-9',
    boss: ['mage'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['mage'],
    sUnit: ['mage'],
  },
  {
    stage: '9-3',
    boss: ['mage'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['ranger'],
    sUnit: ['ranger'],
  },
  {
    stage: '9-6',
    boss: ['healer'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['healer'],
    sUnit: ['healer'],
  },
  {
    stage: '9-9',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['assault'],
    sUnit: ['assault'],
  },
  {
    stage: '10-3',
    boss: ['mage'],
    mats: ['enchants', 'bov', 'runes', 'aot'],
    evos: ['tank'],
    sUnit: null,
  },
  {
    stage: '10-6',
    boss: ['tank'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['tank'],
    sUnit: ['tank'],
  },
  {
    stage: '10-9',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['mage'],
    sUnit: ['mage'],
  },
  {
    stage: '11-3',
    boss: ['assault'],
    mats: ['enchants', 'bov', 'runes', 'aot'],
    evos: ['ranger'],
    sUnit: null,
  },
  {
    stage: '11-6',
    boss: ['tank'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['ranger'],
    sUnit: ['ranger'],
  },
  {
    stage: '11-9',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['healer'],
    sUnit: ['healer'],
  },
  {
    stage: '12-3',
    boss: ['mage'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['assault'],
    sUnit: ['assault'],
  },
  {
    stage: '12-6',
    boss: ['mage'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['tank'],
    sUnit: ['tank'],
  },
  {
    stage: '12-9',
    boss: ['healer'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['mage'],
    sUnit: ['mage'],
  },
  {
    stage: '13-3',
    boss: ['tank'],
    mats: ['enchants', 'bov', 'runes', 'aot'],
    evos: ['healer'],
    sUnit: null,
  },
  {
    stage: '13-6',
    boss: ['ranger'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['ranger'],
    sUnit: ['ranger'],
  },
  {
    stage: '13-9',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['healer'],
    sUnit: ['healer'],
  },
  {
    stage: '14-3',
    boss: ['mage'],
    mats: ['enchants', 'bov', 'runes', 'aot'],
    evos: ['mage'],
    sUnit: null,
  },
  {
    stage: '14-6',
    boss: ['healer'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['assault'],
    sUnit: ['assault'],
  },
  {
    stage: '14-9',
    boss: ['mage'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['tank'],
    sUnit: ['tank'],
  },
  {
    stage: '15-3',
    boss: ['tank'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['mage'],
    sUnit: ['mage'],
  },
  {
    stage: '15-6',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['ranger'],
    sUnit: ['ranger'],
  },
  {
    stage: '15-9',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['healer'],
    sUnit: ['healer'],
  },
  {
    stage: '16-3',
    boss: ['assault'],
    mats: ['enchants', 'bov', 'runes', 'aot'],
    evos: ['ranger'],
    sUnit: null,
  },
  {
    stage: '16-6',
    boss: ['ranger'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['assault'],
    sUnit: ['assault'],
  },
  {
    stage: '16-9',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['tank'],
    sUnit: ['tank'],
  },
  {
    stage: '17-3',
    boss: ['ranger'],
    mats: ['enchants', 'bov', 'runes', 'aot'],
    evos: ['assault'],
    sUnit: null,
  },
  {
    stage: '17-6',
    boss: ['healer'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['mage'],
    sUnit: ['mage'],
  },
  {
    stage: '17-9',
    boss: ['mage'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['ranger'],
    sUnit: ['ranger'],
  },
  {
    stage: '18-3',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['healer'],
    sUnit: ['healer'],
  },
  {
    stage: '18-6',
    boss: ['mage'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['assault'],
    sUnit: ['assault'],
  },
  {
    stage: '18-9',
    boss: ['healer'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['tank'],
    sUnit: ['tank'],
  },
  {
    stage: '19-3',
    boss: ['tank'],
    mats: ['enchants', 'bov', 'runes', 'aot'],
    evos: ['mage'],
    sUnit: null,
  },
  {
    stage: '19-6',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['mage'],
    sUnit: ['mage'],
  },
  {
    stage: '19-9',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['ranger'],
    sUnit: ['ranger'],
  },
  {
    stage: '20-3',
    boss: ['assault'],
    mats: ['enchants', 'bov', 'runes', 'aot'],
    evos: ['tank'],
    sUnit: null,
  },
  {
    stage: '20-6',
    boss: ['healer'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['healer'],
    sUnit: ['healer'],
  },
  {
    stage: '20-9',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['assault'],
    sUnit: ['assault'],
  },
  {
    stage: '21-3',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['tank'],
    sUnit: ['tank'],
  },
  {
    stage: '21-6',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['mage'],
    sUnit: ['mage'],
  },
  {
    stage: '21-9',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['ranger'],
    sUnit: ['ranger'],
  },
  {
    stage: '22-3',
    boss: ['mage'],
    mats: ['enchants', 'bov', 'runes', 'aot'],
    evos: ['assault'],
    sUnit: null,
  },
  {
    stage: '22-6',
    boss: ['ranger'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['healer'],
    sUnit: ['healer'],
  },
  {
    stage: '22-9',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['assault'],
    sUnit: ['assault'],
  },
  {
    stage: '23-3',
    boss: ['tank'],
    mats: ['enchants', 'bov', 'runes', 'aot'],
    evos: ['healer'],
    sUnit: null,
  },
  {
    stage: '23-6',
    boss: ['ranger'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['ranger'],
    sUnit: ['ranger'],
  },
  {
    stage: '23-9',
    boss: ['mage'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['healer'],
    sUnit: ['healer'],
  },
  {
    stage: '24-3',
    boss: ['healer'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['assault'],
    sUnit: ['assault'],
  },
  {
    stage: '24-6',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['tank'],
    sUnit: ['tank'],
  },
  {
    stage: '24-9',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['mage'],
    sUnit: ['mage'],
  },
  {
    stage: '25-3',
    boss: ['tank'],
    mats: ['enchants', 'bov', 'runes', 'aot'],
    evos: ['tank'],
    sUnit: null,
  },
  {
    stage: '25-6',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['ranger'],
    sUnit: ['ranger'],
  },
  {
    stage: '25-9',
    boss: ['mage'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['healer'],
    sUnit: ['healer'],
  },
  {
    stage: '26-3',
    boss: ['assault'],
    mats: ['enchants', 'bov', 'runes', 'aot'],
    evos: ['ranger'],
    sUnit: null,
  },
  {
    stage: '26-6',
    boss: ['ranger'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['mage'],
    sUnit: ['mage'],
  },
  {
    stage: '26-9',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['ranger'],
    sUnit: ['ranger'],
  },
  {
    stage: '27-3',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['healer'],
    sUnit: ['healer'],
  },
  {
    stage: '27-6',
    boss: ['healer'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['assault'],
    sUnit: ['assault'],
  },
  {
    stage: '27-9',
    boss: ['mage'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['tank'],
    sUnit: ['tank'],
  },
  {
    stage: '28-3',
    boss: ['tank'],
    mats: ['enchants', 'bov', 'runes', 'aot'],
    evos: ['assault'],
    sUnit: null,
  },
  {
    stage: '28-6',
    boss: ['assault'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['mage'],
    sUnit: ['mage'],
  },
  {
    stage: '28-9',
    boss: ['mage'],
    mats: ['enchants', 'runes', 'aot'],
    evos: ['ranger'],
    sUnit: ['ranger'],
  },
]

export const evos = ['assault', 'tank', 'ranger', 'mage', 'healer']
export const boss = ['assault', 'tank', 'ranger', 'mage', 'healer']
export const sUnit = ['assault', 'tank', 'ranger', 'mage', 'healer']
export const mats = ['enchants', 'runes', 'bov', 'aot']

export const heroes = [
  {
    id: 'elesis',
    name: 'Elesis',
    pic: elesis2,
    heroColor: '#FDB9B7',
    profilePic: elesisv,
  },
  {
    id: 'lire',
    name: 'Lire',
    pic: lire2,
    heroColor: '#BBFBB1',
    profilePic: lirev,
  },
  {
    id: 'arme',
    name: 'Arme',
    pic: arme2,
    heroColor: '#FCB8F1',
    profilePic: armev,
  },
  {
    id: 'lass',
    name: 'Lass',
    pic: lass2,
    heroColor: '#B7F3F9',
    profilePic: lassv,
  },
  {
    id: 'ryan',
    name: 'Ryan',
    pic: ryan2,
    heroColor: '#FDE2B7',
    profilePic: ryanv,
  },
  {
    id: 'ronan',
    name: 'Ronan',
    pic: ronan2,
    heroColor: '#B9B3F6',
    profilePic: ronanv,
  },
  { id: 'amy', name: 'Amy', pic: amy2, heroColor: '#FBBDDB', profilePic: amyv },
  { id: 'jin', name: 'Jin', pic: jin2, heroColor: '#C53019', profilePic: jinv },
  {
    id: 'sieghart',
    name: 'Sieghart',
    pic: sieghart2,
    heroColor: '#48384F',
    profilePic: sieghartv,
  },
  {
    id: 'mari',
    name: 'Mari',
    pic: mari2,
    heroColor: '#5188E9',
    profilePic: mariv,
  },
  { id: 'dio', name: 'Dio', pic: dio2, heroColor: '#D75ED1', profilePic: diov },
  {
    id: 'zero',
    name: 'Zero',
    pic: zero2,
    heroColor: '#D8E4A9',
    profilePic: zerov,
  },
  { id: 'ley', name: 'Ley', pic: ley2, heroColor: '#BC77DC', profilePic: leyv },
  {
    id: 'rufus',
    name: 'Rufus',
    pic: rufus2,
    heroColor: '#B14953',
    profilePic: rufusv,
  },
  { id: 'rin', name: 'Rin', pic: rin2, heroColor: '#30D1ED', profilePic: rinv },
  {
    id: 'asin',
    name: 'Asin',
    pic: asin2,
    heroColor: '#BFDADA',
    profilePic: asinv,
  },
  {
    id: 'lime',
    name: 'Lime',
    pic: lime2,
    heroColor: '#B7EEA3',
    profilePic: limev,
  },
  {
    id: 'edel',
    name: 'Edel',
    pic: edel2,
    heroColor: '#5181B8',
    profilePic: edelv,
  },
  {
    id: 'veigas',
    name: 'Veigas',
    pic: veigas2,
    heroColor: '#E7C8E9',
    profilePic: veigasv,
  },
  {
    id: 'serdin',
    name: 'Serdin',
    pic: serdin2,
    heroColor: '#C7EADE',
    profilePic: serdinv,
  },
  {
    id: 'kanavan',
    name: 'Kanavan',
    pic: kanavan2,
    heroColor: '#F69AD6',
    profilePic: kanavanv,
  },
  {
    id: 'werner',
    name: 'Werner',
    pic: werner2,
    heroColor: '#CB9CE8',
    profilePic: wernerv,
  },
  {
    id: 'grandiel',
    name: 'Grandiel',
    pic: grandiel2,
    heroColor: '#A0D6E8',
    profilePic: grandielv,
  },
  {
    id: 'nelia',
    name: 'Nelia',
    pic: nelia2,
    heroColor: '#E38699',
    profilePic: neliav,
  },
  { id: 'io', name: 'Io', pic: io2, heroColor: '#4CCFFF', profilePic: iov },
  {
    id: 'hwarin',
    name: 'Hwarin',
    pic: hwarin2,
    heroColor: '#FCCFEC',
    profilePic: hwarinv,
  },
  {
    id: 'europa',
    name: 'Europa',
    pic: europa2,
    heroColor: '#BFF9BC',
    profilePic: europav,
  },
  {
    id: 'tia',
    name: 'Tia',
    pic: tia2,
    heroColor: '#AEC5FD',
    profilePic: tiav,
  },
  {
    id: 'gaian',
    name: 'Gaian',
    pic: gaian2,
    heroColor: '#E3DFF4',
    profilePic: gaianv,
  },
  {
    id: 'arsad',
    name: 'Arsad',
    pic: arsad2,
    heroColor: '#FFEE9D',
    profilePic: arsadv,
  },
]

export const heroBuilds = {
  elesis: {
    id: 'elesis',
    name: 'Elesis',
    rank: sr,
    type: 'assault',
    color: '#C12119',
    classPic: assault,
    pet: elion,
    petName: 'Elion',
    set: 'Power of Anger (blue)',
    setColor: '#4E28D0',
    pic: elesis,
    limitBreak1: elesiss2,
    limitBreak2: elesispass,
    lb1: 'S2',
    lb2: 'Passive',
    ring: solar,
    ringName: 'Solar Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: cdr,
    tn1: 'CDR',
    trait2: crit,
    tn2: 'Crit',
    trait3: sadi,
    tn3: 'SADI',
    socket1: 'Physical Attack',
    socket2: 'CDR',
    socket3: 'SADI',
    chaser05: prayerofblessing,
    chaser10: pureluck,
    chaser15: impulse,
    chaser20: elesischaser,
    chaser25: fate,
    artifact: assaulta,
    artifactName: 'Assault',
    fluffy: elesisfluffy,
  },
  lire: {
    id: 'lire',
    name: 'Lire',
    rank: sr,
    type: 'ranger',
    color: '#5EDB51',
    classPic: ranger,
    pet: reruby,
    petName: 'Reruby',
    set: 'Vows of Violence (green)',
    setColor: '#4C9B60',
    pic: lire,
    limitBreak1: lires2,
    limitBreak2: lirepass,
    lb1: 'S2',
    lb2: 'Passive',
    ring: gale,
    ringName: 'Gale Ring',
    necklace: lava,
    necklaceName: 'Lava Necklace',
    earrings: gust,
    earringsName: 'Earrings of Gust',
    trait1: basi,
    tn1: 'BASI',
    trait2: cdr,
    tn2: 'CDR',
    trait3: badi,
    tn3: 'BADI',
    socket1: 'Physical Attack',
    socket2: 'BASI',
    socket3: 'BADI',
    chaser05: elevatedpower,
    chaser10: fate,
    chaser15: impulse,
    chaser20: lirechaser,
    chaser25: invisiblehand,
    artifact: rangera,
    artifactName: 'Ranger',
    fluffy: lirefluffy,
  },
  arme: {
    id: 'arme',
    name: 'Arme',
    rank: sr,
    type: 'mage',
    color: '#8242A5',
    classPic: mage,
    pet: almong,
    petName: 'Almong',
    set: 'Dagger of Passion (orange)',
    setColor: '#DF7B0E',
    pic: arme,
    limitBreak1: armepass,
    limitBreak2: armes1,
    lb1: 'Passive',
    lb2: 'S1',
    ring: solar,
    ringName: 'Solar Ring',
    necklace: lava,
    necklaceName: 'Lava Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: crit,
    tn1: 'Crit',
    trait2: cdr,
    tn2: 'CDR',
    trait3: sadi,
    tn3: 'SADI',
    socket1: 'Magic Attack',
    socket2: 'CDR',
    socket3: 'SADI',
    chaser05: elevatedpower,
    chaser10: fate,
    chaser15: impulse,
    chaser20: armechaser,
    chaser25: pureluck,
    artifact: magea,
    artifactName: 'Mage',
    fluffy: armefluffy,
  },
  lass: {
    id: 'lass',
    name: 'Lass',
    rank: sr,
    type: 'assault',
    color: '#C12119',
    classPic: assault,
    pet: raul,
    petName: 'Raul',
    set: 'Dagger of Passion (orange)',
    setColor: '#DF7B0E',
    pic: lass,
    limitBreak1: lasss2,
    limitBreak2: lasspass,
    lb1: 'S2',
    lb2: 'Passive',
    ring: solar,
    ringName: 'Solar Ring',
    necklace: lava,
    necklaceName: 'Lava Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: crit,
    tn1: 'Crit',
    trait2: cdr,
    tn2: 'CDR',
    trait3: sadi,
    tn3: 'SADI',
    socket1: 'Physical Attack',
    socket2: 'Crit',
    socket3: 'SADI',
    chaser05: elevatedpower,
    chaser10: fate,
    chaser15: impulse,
    chaser20: lasschaser,
    chaser25: pureluck,
    artifact: assaulta,
    artifactName: 'Assault',
    fluffy: lassfluffy,
  },
  ryan: {
    id: 'ryan',
    name: 'Ryan',
    rank: sr,
    type: 'tank',
    color: '#0C9AFF',
    classPic: tank,
    pet: montero,
    petName: 'Montero',
    set: 'Power of Anger (blue)',
    setColor: '#4E28D0',
    pic: ryan,
    limitBreak1: ryans1,
    limitBreak2: ryans2,
    lb1: 'S1',
    lb2: 'S2',
    ring: glacial,
    ringName: 'Glacial Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: badr,
    tn1: 'BADR',
    trait2: sadr,
    tn2: 'SADR',
    trait3: cdr,
    tn3: 'CDR',
    socket1: 'Max Health',
    socket2: 'CDR',
    socket3: 'BADR/SADR',
    chaser05: prayerofblessing,
    chaser10: longlife,
    chaser15: impulse,
    chaser20: ryanchaser,
    chaser25: breathoflife,
    artifact: tanka,
    artifactName: 'Tank',
    fluffy: ryanfluffy,
  },
  ronan: {
    id: 'ronan',
    name: 'Ronan',
    rank: sr,
    type: 'tank',
    color: '#0C9AFF',
    classPic: tank,
    pet: temphy,
    petName: 'Temphy',
    set: 'Power of Anger (blue)',
    setColor: '#4E28D0',
    pic: ronan,
    limitBreak1: ronans2,
    limitBreak2: ronanpass,
    lb1: 'S2',
    lb2: 'Passive',
    ring: glacial,
    ringName: 'Glacial Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: cdr,
    tn1: 'CDR',
    trait2: badr,
    tn2: 'BADR',
    trait3: sadr,
    tn3: 'SADR',
    socket1: 'Max Health',
    socket2: 'CDR',
    socket3: 'BADR/SADR',
    chaser05: prayerofblessing,
    chaser10: divineprotection,
    chaser15: impulse,
    chaser20: ronanchaser,
    chaser25: longlife,
    artifact: tanka,
    artifactName: 'Tank',
    fluffy: ronanfluffy,
  },
  amy: {
    id: 'amy',
    name: 'Amy',
    rank: sr,
    type: 'healer',
    color: '#FFE228',
    classPic: healer,
    pet: muse,
    petName: 'Muse',
    set: 'Vows of Violence (green)',
    setColor: '#4C9B60',
    pic: amy,
    limitBreak1: amys1,
    limitBreak2: amypass,
    lb1: 'S1',
    lb2: 'Passive',
    ring: gale,
    ringName: 'Gale Rings',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: cdr,
    tn1: 'CDR',
    trait2: basi,
    tn2: 'BASI',
    trait3: sadi,
    tn3: 'SADI',
    socket1: 'Magic Attack',
    socket2: 'CDR/BASI',
    socket3: 'SADI',
    chaser05: prayerofblessing,
    chaser10: invisiblehand,
    chaser15: impulse,
    chaser20: amychaser,
    chaser25: helper,
    artifact: healera,
    artifactName: 'Healer',
    fluffy: amyfluffy,
  },
  jin: {
    id: 'jin',
    name: 'Jin',
    rank: sr,
    type: 'tank',
    color: '#0C9AFF',
    classPic: tank,
    pet: hoya,
    petName: 'Hoya',
    set: 'Dagger of Passion (orange)',
    setColor: '#DF7B0E',
    pic: jin,
    limitBreak1: jins1,
    limitBreak2: jins2,
    lb1: 'S1',
    lb2: 'S2',
    ring: solar,
    ringName: 'Solar Ring',
    necklace: lava,
    necklaceName: 'Lava Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: crit,
    tn1: 'Crit',
    trait2: cdr,
    tn2: 'CDR',
    trait3: sadr,
    tn3: 'SADR',
    socket1: 'Physical Attack',
    socket2: 'CDR/Crit',
    socket3: 'SADI',
    chaser05: prayerofblessing,
    chaser10: impulse,
    chaser15: fate,
    chaser20: jinchaser,
    chaser25: elevatedpower,
    artifact: tanka,
    artifactName: 'Tank',
    fluffy: jinfluffy,
  },
  sieghart: {
    id: 'sieghart',
    name: 'Sieghart',
    rank: sr,
    type: 'assault',
    color: '#C12119',
    classPic: assault,
    pet: hunt,
    petName: 'Hunt',
    set: 'Dagger of Passion (orange)',
    setColor: '#DF7B0E',
    pic: sieghart,
    limitBreak1: sieghartpass,
    limitBreak2: siegharts1,
    lb1: 'Passive',
    lb2: 'S1',
    ring: solar,
    ringName: 'Solar Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: sadr,
    tn1: 'SADR',
    trait2: cdr,
    tn2: 'CDR',
    trait3: badr,
    tn3: 'BADR',
    socket1: 'Physical Attack',
    socket2: 'CDR',
    socket3: 'SADI',
    chaser05: longlife,
    chaser10: persistentexecutioner,
    chaser15: impulse,
    chaser20: sieghartchaser,
    chaser25: fate,
    artifact: assaulta,
    artifactName: 'Assault',
    fluffy: sieghartfluffy,
  },
  mari: {
    id: 'mari',
    name: 'Mari',
    rank: sr,
    type: 'mage',
    color: '#8242A5',
    classPic: mage,
    pet: tcon,
    petName: 'T-Con',
    set: 'Dagger of Passion (orange)',
    setColor: '#DF7B0E',
    pic: mari,
    limitBreak1: maris1,
    limitBreak2: maripass,
    lb1: 'S1',
    lb2: 'Passive',
    ring: solar,
    ringName: 'Solar Ring',
    necklace: lava,
    necklaceName: 'Lava Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: crit,
    tn1: 'Crit',
    trait2: cdr,
    tn2: 'CDR',
    trait3: sadi,
    tn3: 'SADI',
    socket1: 'Magic Attack',
    socket2: 'Crit/CDR',
    socket3: 'SADI',
    chaser05: elevatedpower,
    chaser10: fate,
    chaser15: impulse,
    chaser20: marichaser,
    chaser25: prayerofblessing,
    artifact: magea,
    artifactName: 'Mage',
    fluffy: marifluffy,
  },
  dio: {
    id: 'dio',
    name: 'Dio',
    rank: sr,
    type: 'assault',
    color: '#C12119',
    classPic: assault,
    pet: dangel,
    petName: 'Dangel',
    set: 'Power of Anger (blue)',
    setColor: '#4E28D0',
    pic: dio,
    limitBreak1: dios1,
    limitBreak2: diopass,
    lb1: 'S1',
    lb2: 'Passive',
    ring: gale,
    ringName: 'Gale Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: cdr,
    tn1: 'CDR',
    trait2: basi,
    tn2: 'BASI',
    trait3: sadr,
    tn3: 'SADR',
    socket1: 'Physical Attack',
    socket2: 'CDR',
    socket3: 'SADI',
    chaser05: prayerofblessing,
    chaser10: impulse,
    chaser15: persistentexecutioner,
    chaser20: diochaser,
    chaser25: longlife,
    artifact: assaulta,
    artifactName: 'Assault',
    fluffy: diofluffy,
  },
  zero: {
    id: 'zero',
    name: 'Zero',
    rank: sr,
    type: 'tank',
    color: '#0C9AFF',
    classPic: tank,
    pet: zeta,
    petName: 'Zeta',
    set: 'Dagger of Passion (orange)',
    setColor: '#DF7B0E',
    pic: zero,
    limitBreak1: zeros1,
    limitBreak2: zeropass,
    lb1: 'S1',
    lb2: 'Passive',
    ring: solar,
    ringName: 'Solar Ring',
    necklace: lava,
    necklaceName: 'Lava Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: crit,
    tn1: 'Crit',
    trait2: cdr,
    tn2: 'CDR',
    trait3: sadr,
    tn3: 'SADR',
    socket1: 'Max Health',
    socket2: 'Crit',
    socket3: 'SADR/BADR',
    chaser05: prayerofblessing,
    chaser10: divineprotection,
    chaser15: impulse,
    chaser20: zerochaser,
    chaser25: longlife,
    artifact: tanka,
    artifactName: 'Tank',
    fluffy: zerofluffy,
  },
  ley: {
    id: 'ley',
    name: 'Ley',
    rank: sr,
    type: 'mage',
    color: '#8242A5',
    classPic: mage,
    pet: sebastian,
    petName: 'Sebastian',
    set: 'Vows of Violence (green)',
    setColor: '#4C9B60',
    pic: ley,
    limitBreak1: leys2,
    limitBreak2: leypass,
    lb1: 'S2',
    lb2: 'Passive',
    ring: gale,
    ringName: 'Gale Ring',
    necklace: lava,
    necklaceName: 'Lava Necklace',
    earrings: gust,
    earringsName: 'Earrings of Gust',
    trait1: crit,
    tn1: 'Crit',
    trait2: basi,
    tn2: 'BASI',
    trait3: badi,
    tn3: 'BADI',
    socket1: 'Magic Attack',
    socket2: 'BASI',
    socket3: 'SADI',
    chaser05: elevatedpower,
    chaser10: fate,
    chaser15: impulse,
    chaser20: leychaser,
    chaser25: invisiblehand,
    artifact: magea,
    artifactName: 'Mage',
    fluffy: leyfluffy,
  },
  rufus: {
    id: 'rufus',
    name: 'Rufus',
    rank: sr,
    type: 'ranger',
    color: '#5EDB51',
    classPic: ranger,
    pet: rupe,
    petName: 'Rupe',
    set: 'Vows of Violence (green)',
    setColor: '#4C9B60',
    pic: rufus,
    limitBreak1: rufuss1,
    limitBreak2: rufuspass,
    lb1: 'S1',
    lb2: 'Passive',
    ring: gale,
    ringName: 'Gale Ring',
    necklace: lava,
    necklaceName: 'Lava Necklace',
    earrings: gust,
    earringsName: 'Earrings of Gust',
    trait1: crit,
    tn1: 'Crit',
    trait2: basi,
    tn2: 'BASI',
    trait3: badi,
    tn3: 'BADI',
    socket1: 'Physical Attack',
    socket2: 'Crit',
    socket3: 'SADI',
    chaser05: prayerofblessing,
    chaser10: fate,
    chaser15: impulse,
    chaser20: rufuschaser,
    chaser25: elevatedpower,
    artifact: rangera,
    artifactName: 'Ranger',
    fluffy: rufusfluffy,
  },
  rin: {
    id: 'rin',
    name: 'Rin',
    rank: sr,
    type: 'healer',
    color: '#FFE228',
    classPic: healer,
    pet: niah,
    petName: 'Niah',
    set: 'Power of Anger (blue)',
    setColor: '#4E28D0',
    pic: rin,
    limitBreak1: rins1,
    limitBreak2: rins2,
    lb1: 'S1',
    lb2: 'S2',
    ring: solar,
    ringName: 'Solar Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: crit,
    tn1: 'Crit',
    trait2: cdr,
    tn2: 'CDR',
    trait3: sadi,
    tn3: 'SADI',
    socket1: 'Max Health',
    socket2: 'CDR/Crit',
    socket3: 'SADR/BADR',
    chaser05: longlife,
    chaser10: breathoflife,
    chaser15: impulse,
    chaser20: rinchaser,
    chaser25: prayerofblessing,
    artifact: healera,
    artifactName: 'Healer',
    fluffy: rinfluffy,
  },
  asin: {
    id: 'asin',
    name: 'Asin',
    rank: sr,
    type: 'tank',
    color: '#0C9AFF',
    classPic: tank,
    pet: shin,
    petName: 'Sinn',
    set: 'Power of Anger (blue)',
    setColor: '#4E28D0',
    pic: asin,
    limitBreak1: asins2,
    limitBreak2: asinpass,
    lb1: 'S2',
    lb2: 'Passive',
    ring: glacial,
    ringName: 'Glacial Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: cdr,
    tn1: 'CDR',
    trait2: sadr,
    tn2: 'SADR',
    trait3: badr,
    tn3: 'BADR',
    socket1: 'Max Health',
    socket2: 'CDR',
    socket3: 'BADR/SADR',
    chaser05: prayerofblessing,
    chaser10: impulse,
    chaser15: fate,
    chaser20: asinchaser,
    chaser25: elevatedpower,
    artifact: tanka,
    artifactName: 'Tank',
    fluffy: asinfluffy,
  },
  lime: {
    id: 'lime',
    name: 'Lime',
    rank: sr,
    type: 'healer',
    color: '#FFE228',
    classPic: healer,
    pet: holy,
    petName: 'Holy',
    set: 'Power of Anger (blue)',
    setColor: '#4E28D0',
    pic: lime,
    limitBreak1: limepass,
    limitBreak2: limes2,
    lb1: 'Passive',
    lb2: 'S2',
    ring: glacial,
    ringName: 'Glacial Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: cdr,
    tn1: 'CDR',
    trait2: sadi,
    tn2: 'SADI',
    trait3: sadr,
    tn3: 'SADR',
    socket1: 'Max Health',
    socket2: 'CDR',
    socket3: 'SADR/BADR',
    chaser05: prayerofblessing,
    chaser10: longlife,
    chaser15: impulse,
    chaser20: limechaser,
    chaser25: fate,
    artifact: healera,
    artifactName: 'Healer',
    fluffy: limefluffy,
  },
  edel: {
    id: 'edel',
    name: 'Edel',
    rank: sr,
    type: 'assault',
    color: '#C12119',
    classPic: assault,
    pet: dia,
    petName: 'Dia',
    set: 'Vows of Violence (green)',
    setColor: '#4C9B60',
    pic: edel,
    limitBreak1: edels2,
    limitBreak2: edelpass,
    lb1: 'S2',
    lb2: 'Passive',
    ring: gale,
    ringName: 'Gale Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: gust,
    earringsName: 'Earrings of Gust',
    trait1: cdr,
    tn1: 'CDR',
    trait2: basi,
    tn2: 'BASI',
    trait3: badi,
    tn3: 'BADI',
    socket1: 'Physical Attack',
    socket2: 'BASI/CDR',
    socket3: 'BADI/SADI',
    chaser05: prayerofblessing,
    chaser10: impulse,
    chaser15: fate,
    chaser20: edelchaser,
    chaser25: invisiblehand,
    artifact: assaulta,
    artifactName: 'Assault',
    fluffy: edelfluffy,
  },
  veigas: {
    id: 'veigas',
    name: 'Veigas',
    rank: sr,
    type: 'mage',
    color: '#8242A5',
    classPic: mage,
    pet: crocell,
    petName: 'Crocell',
    set: 'Dagger of Passion (orange)',
    setColor: '#DF7B0E',
    pic: veigas,
    limitBreak1: veigass1,
    limitBreak2: veigaspass,
    lb1: 'S1',
    lb2: 'Passive',
    ring: solar,
    ringName: 'Solar Ring',
    necklace: lava,
    necklaceName: 'Lava Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: crit,
    tn1: 'Crit',
    trait2: cdr,
    tn2: 'CDR',
    trait3: sadi,
    tn3: 'SADI',
    socket1: 'Magic Attack',
    socket2: 'Crit/CDR',
    socket3: 'SADI',
    chaser05: elevatedpower,
    chaser10: fate,
    chaser15: impulse,
    chaser20: veigaschaser,
    chaser25: pureluck,
    artifact: magea,
    artifactName: 'Mage',
    fluffy: veigasfluffy,
  },
  serdin: {
    id: 'serdin',
    name: 'Serdin',
    rank: sr,
    type: 'healer',
    color: '#FFE228',
    classPic: healer,
    pet: sally,
    petName: 'Sally',
    set: 'Power of Anger (blue)',
    setColor: '#4E28D0',
    pic: serdin,
    limitBreak1: serdins2,
    limitBreak2: serdins1,
    lb1: 'S2',
    lb2: 'S1',
    ring: gale,
    ringName: 'Gale Ring',
    necklace: lava,
    necklaceName: 'Lava Necklace',
    earrings: gust,
    earringsName: 'Earrings of Gust',
    trait1: cdr,
    tn1: 'CDR',
    trait2: basi,
    tn2: 'BASI',
    trait3: sadi,
    tn3: 'SADI',
    socket1: 'Magic Attack',
    socket2: 'CDR/BASI',
    socket3: 'SADR/BADI',
    chaser05: prayerofblessing,
    chaser10: longlife,
    chaser15: impulse,
    chaser20: serdinchaser,
    chaser25: fate,
    artifact: healera,
    artifactName: 'Healer',
    fluffy: serdinfluffy,
  },
  kanavan: {
    id: 'kanavan',
    name: 'Kanavan',
    rank: sr,
    type: 'assault',
    color: '#C12119',
    classPic: assault,
    pet: gnar,
    petName: 'Gnar',
    set: 'Dagger of Passion (orange)',
    setColor: '#DF7B0E',
    pic: kanavan,
    limitBreak1: kanavans2,
    limitBreak2: kanavans1,
    lb1: 'S2',
    lb2: 'S1',
    ring: solar,
    ringName: 'Solar Ring',
    necklace: lava,
    necklaceName: 'Lava Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: crit,
    tn1: 'Crit',
    trait2: cdr,
    tn2: 'CDR',
    trait3: sadi,
    tn3: 'SADI',
    socket1: 'Physical Attack',
    socket2: 'Crit/BASI/CDR',
    socket3: 'SADI',
    chaser05: elevatedpower,
    chaser10: impulse,
    chaser15: fate,
    chaser20: kanavanchaser,
    chaser25: pureluck,
    artifact: assaulta,
    artifactName: 'Assault',
    fluffy: kanavanfluffy,
  },
  werner: {
    id: 'werner',
    name: 'Werner',
    rank: sr,
    type: 'ranger',
    color: '#5EDB51',
    classPic: ranger,
    pet: goldporkcard,
    petName: 'Gold Pork',
    set: 'Spirit of Luck (pink)',
    setColor: '#AC3A98',
    pic: werner,
    limitBreak1: wernerpass,
    limitBreak2: werners2,
    lb1: 'Passive',
    lb2: 'S2',
    ring: solar,
    ringName: 'Solar Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: crit,
    tn1: 'Crit',
    trait2: cdr,
    tn2: 'CDR',
    trait3: badi,
    tn3: 'BADI',
    socket1: 'Physical Attack',
    socket2: 'CDR/Crit',
    socket3: 'BADI',
    chaser05: pureluck,
    chaser10: fate,
    chaser15: impulse,
    chaser20: wernerchaser,
    chaser25: elevatedpower,
    artifact: rangera,
    artifactName: 'Ranger',
    fluffy: wernerfluffy,
  },
  grandiel: {
    id: 'grandiel',
    name: 'Grandiel',
    rank: sr,
    type: 'healer',
    color: '#FFE228',
    classPic: healer,
    pet: luce,
    petName: 'Luche',
    set: 'Power of Anger (blue)',
    setColor: '#4E28D0',
    pic: grandiel,
    limitBreak1: grandiels2,
    limitBreak2: grandiels1,
    lb1: 'S2',
    lb2: 'S1',
    ring: glacial,
    ringName: 'Glacial Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: cdr,
    tn1: 'CDR',
    trait2: sadr,
    tn2: 'SADR',
    trait3: badr,
    tn3: 'BADR',
    socket1: 'Magic Attack',
    socket2: 'CDR',
    socket3: 'SADR',
    chaser05: longlife,
    chaser10: prayerofblessing,
    chaser15: impulse,
    chaser20: grandielchaser,
    chaser25: breathoflife,
    artifact: healera,
    artifactName: 'Healer',
    fluffy: grandielfluffy,
  },
  nelia: {
    id: 'nelia',
    name: 'Nelia',
    rank: sr,
    type: 'mage',
    color: '#8242A5',
    classPic: mage,
    pet: nelion,
    petName: 'Nelion',
    set: 'Dagger of Passion (orange)',
    setColor: '#DF7B0E',
    pic: nelia,
    limitBreak1: nelias2,
    limitBreak2: neliapass,
    lb1: 'S2',
    lb2: 'Passive',
    ring: solar,
    ringName: 'Solar Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: crit,
    tn1: 'Crit',
    trait2: cdr,
    tn2: 'CDR',
    trait3: sadi,
    tn3: 'SADI',
    socket1: 'Magic Attack,',
    socket2: 'CDR',
    socket3: 'SADI',
    chaser05: prayerofblessing,
    chaser10: fate,
    chaser15: impulse,
    chaser20: neliachaser,
    chaser25: elevatedpower,
    artifact: magea,
    artifactName: 'Mage',
    fluffy: neliafluffy,
  },
  io: {
    id: 'io',
    name: 'Io',
    rank: sr,
    type: 'ranger',
    color: '#5EDB51',
    classPic: ranger,
    pet: luri,
    petName: 'Ruri',
    set: 'Vows of Violence (green) or Power of Anger (blue)',
    setColor: '#4C9B60',
    pic: io,
    limitBreak1: ios1,
    limitBreak2: iopass,
    lb1: 'S1',
    lb2: 'Passive',
    ring: gale,
    ringName: 'Gale Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: gust,
    earringsName: 'Earrings of Gust',
    trait1: cdr,
    tn1: 'CDR',
    trait2: basi,
    tn2: 'BASI',
    trait3: sadi,
    tn3: 'SADI',
    socket1: 'Physical Attack',
    socket2: 'BASI/CDR/Crit',
    socket3: 'BADI',
    chaser05: prayerofblessing,
    chaser10: fate,
    chaser15: impulse,
    chaser20: iochaser,
    chaser25: elevatedpower,
    artifact: rangera,
    artifactName: 'Ranger',
    fluffy: iofluffy,
  },
  hwarin: {
    id: 'hwarin',
    name: 'Hwarin',
    rank: sr,
    type: 'healer',
    color: '#FFE228',
    classPic: healer,
    pet: hwarang,
    petName: 'Hwarang',
    set: 'Power of Anger (blue)',
    setColor: '#4E28D0',
    pic: hwarin,
    limitBreak1: hwarins2,
    limitBreak2: hwarinpass,
    lb1: 'S2',
    lb2: 'Passive',
    ring: glacial,
    ringName: 'Glacial Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: cdr,
    tn1: 'CDR',
    trait2: sadr,
    tn2: 'SADR',
    trait3: badr,
    tn3: 'BADR',
    socket1: 'Max Health',
    socket2: 'CDR',
    socket3: 'SADR/BADR',
    chaser05: longlife,
    chaser10: prayerofblessing,
    chaser15: impulse,
    chaser20: hwarinchaser,
    chaser25: fate,
    artifact: healera,
    artifactName: 'Healer',
  },
  europa: {
    id: 'europa',
    name: 'Europa',
    rank: sr,
    type: 'assault',
    color: '#C12119',
    classPic: assault,
    pet: howl,
    petName: 'Howl',
    set: 'Dagger of Passion (orange)',
    setColor: '#DF7B0E',
    pic: europa,
    limitBreak1: europapassive,
    limitBreak2: europas1,
    lb1: 'Passive',
    lb2: 'S1',
    ring: solar,
    ringName: 'Solar Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: cdr,
    tn1: 'CDR',
    trait2: crit,
    tn2: 'Crit',
    trait3: sadi,
    tn3: 'SADI',
    socket1: 'Physical Attack',
    socket2: 'CDR/Crit',
    socket3: 'SADI',
    chaser05: prayerofblessing,
    chaser10: fate,
    chaser15: impulse,
    chaser20: europachaser,
    chaser25: persistentexecutioner,
    artifact: assaulta,
    artifactName: 'Assault',
  },
  tia: {
    id: 'tia',
    name: 'Tia',
    rank: sr,
    type: 'tank',
    color: '#0C9AFF',
    classPic: tank,
    pet: pion,
    petName: 'Pion',
    set: 'Dagger of Passion (orange)',
    setColor: '#DF7B0E',
    pic: tia,
    limitBreak1: tias2,
    limitBreak2: tiapassive,
    lb1: 'S2',
    lb2: 'Passive',
    ring: glacial,
    ringName: 'Glacial Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: cdr,
    tn1: 'CDR',
    trait2: sadr,
    tn2: 'SADR',
    trait3: badr,
    tn3: 'BADR',
    socket1: 'Max Health',
    socket2: 'CDR',
    socket3: 'SADR/BADR',
    chaser05: prayerofblessing,
    chaser10: divineprotection,
    chaser15: impulse,
    chaser20: tiachaser,
    chaser25: longlife,
    artifact: tanka,
    artifactName: 'Tank',
  },
  gaian: {
    id: 'darkGaian',
    name: 'Dark Gaian',
    rank: sr,
    type: 'mage',
    color: '#8242A5',
    classPic: mage,
    pet: res,
    petName: 'Res',
    set: 'Dagger of Passion (orange)',
    setColor: '#DF7B0E',
    pic: gaian,
    limitBreak1: '',
    limitBreak2: '',
    lb1: 'N/A',
    lb2: 'N/A',
    ring: sapling,
    ringName: 'Sapling Ring',
    necklace: lifeblood,
    necklaceName: 'Lifeblood Necklace',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: crit,
    tn1: 'Crit',
    trait2: sadi,
    tn2: 'SADI',
    trait3: csr,
    tn3: 'CSR',
    socket1: 'Magic Attack',
    socket2: 'CSR',
    socket3: 'SADI',
    chaser05: '',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
    artifact: magea,
    artifactName: 'Mage',
    fluffy: gaianfluffy,
  },
  arsad: {
    id: 'arsad',
    name: 'Arsad',
    rank: sr,
    type: 'tank',
    color: '#0C9AFF',
    classPic: tank,
    pet: manbo,
    petName: 'Manbo',
    set: 'Power of Anger (blue)',
    setColor: '#4E28D0',
    pic: arsad,
    limitBreak1: '',
    limitBreak2: '',
    lb1: 'N/A',
    lb2: 'N/A',
    ring: glacial,
    ringName: 'Glacial Ring',
    necklace: chasm,
    necklaceName: 'Chasm Necklaces',
    earrings: order,
    earringsName: 'Earrings of Order',
    trait1: cdr,
    tn1: 'CDR',
    trait2: badr,
    tn2: 'BADR',
    trait3: sadr,
    tn3: 'SADR',
    socket1: 'Max Health',
    socket2: 'CDR',
    socket3: 'SADR',
    chaser05: '',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
    artifact: tanka,
    artifactName: 'Tank',
    fluffy: arsadfluffy,
  },
}

export const worldBossTeams = [
  {
    name: 'Meeting Harkion',
    slotOne: wbelesis,
    slotTwo: wblass,
    slotThree: wblire,
    slotFour: wbrufus,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: reruby,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
  },
  {
    name: 'Duel With Harkion',
    slotOne: wbio,
    slotTwo: wbveigas,
    slotThree: wbarme,
    slotFour: wbamy,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: almong,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
  },
  {
    name: 'Final Battle With Harkion',
    slotOne: wbgrandiel,
    slotTwo: wbmari,
    slotThree: wbnelia,
    slotFour: wbedel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: hoya,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
  },
]

export const altarOfTime = [
  {
    name: 'Relay',
    slotOne: wbmari,
    slotTwo: wbio,
    slotThree: wbronan,
    slotFour: wbamy,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: marifa,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: relay,
    color: 'rgba(98,42,101,.5)',
  },
  {
    name: 'Brawl',
    slotOne: wbveigas,
    slotTwo: wbnelia,
    slotThree: wbley,
    slotFour: wbjin,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: muse,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: brawl,
    color: 'rgba(87,128,48,.5)',
  },
  {
    name: 'Elite',
    slotOne: wbryan,
    slotTwo: wbrufus,
    slotThree: wbrin,
    slotFour: wbhwarin,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: rupe,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: elite,
    color: 'rgba(69,48,113,.5)',
  },
  {
    name: 'Boss',
    slotOne: wbelesis,
    slotTwo: wbedel,
    slotThree: wblire,
    slotFour: wblime,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: bossfight,
    color: 'rgba(49,42,93,.5)',
  },
]

export const currentRaid = 'Tower of Disappearance'

export const raidTeam = [
  {
    name: 'Seal In Illusion',
    slotOne: wbzero,
    slotTwo: wbasin,
    slotThree: wblire,
    slotFour: wbserdin,
    oneStars: t6,
    twoStars: t3,
    threeStars: t6,
    fourStars: t3,
    pet: reruby,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: swayingambition,
  },
  {
    name: 'To The Shadow of Corruption',
    slotOne: wbzero,
    slotTwo: wbasin,
    slotThree: wbnelia,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t3,
    threeStars: t6,
    fourStars: t3,
    pet: muse,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: illusionofmemory,
  },
  {
    name: 'Tower Gatekeeper',
    slotOne: wbelesis,
    slotTwo: wbronan,
    slotThree: wblire,
    slotFour: wbamy,
    oneStars: t6,
    twoStars: t3,
    threeStars: t6,
    fourStars: t6,
    pet: muse,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: towermanager,
  },
  {
    name: 'Identical',
    slotOne: wbelesis,
    slotTwo: wbasin,
    slotThree: wbnelia,
    slotFour: wblire,
    oneStars: t6,
    twoStars: t3,
    threeStars: t6,
    fourStars: t6,
    pet: muse,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: rulersrights,
  },
  {
    name: 'Power Beyond Dimension',
    slotOne: wbelesis,
    slotTwo: wbasin,
    slotThree: wbnelia,
    slotFour: wblire,
    oneStars: t6,
    twoStars: t3,
    threeStars: t6,
    fourStars: t6,
    pet: muse,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: resurrectionceremony,
  },
  {
    name: 'Uninvited Guest',
    slotOne: wbzero,
    slotTwo: wbasin,
    slotThree: wbnelia,
    slotFour: wblire,
    oneStars: t6,
    twoStars: t3,
    threeStars: t6,
    fourStars: t6,
    pet: muse,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: castedshadow,
  },
  {
    name: 'Dream of a Butterfly',
    slotOne: wbelesis,
    slotTwo: wbasin,
    slotThree: wblire,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t3,
    threeStars: t6,
    fourStars: t3,
    pet: shin,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: crazyenvoy2,
  },
]

export const dualRaid = 'Rank 7'

export const dualTeams = [
  {
    name: 'Dream of a Butterfly',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    pet2: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: crazyenvoy,
  },
  {
    name: 'Crazy Envoy',
    slotOne: wbronan,
    slotTwo: wbmari,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    pet2: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: crazyenvoy,
  },
  {
    name: 'Contract Terminated',
    slotOne: wbasin,
    slotTwo: wblire,
    slotThree: wbzero,
    slotFour: wbgrandiel,
    oneStars: t3,
    twoStars: t6,
    threeStars: t6,
    fourStars: t3,
    pet: holy,
    pet2: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: crazyenvoy,
  },
  {
    name: 'Between Calm and Passion',
    slotOne: wbasin,
    slotTwo: wbzero,
    slotThree: wbnelia,
    slotFour: wbgrandiel,
    oneStars: t3,
    twoStars: t6,
    threeStars: t6,
    fourStars: t3,
    pet: holy,
    pet2: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: crazyenvoy,
  },
  {
    name: 'New World',
    slotOne: wbasin,
    slotTwo: wbelesis,
    slotThree: wbnelia,
    slotFour: wbgrandiel,
    oneStars: t3,
    twoStars: t6,
    threeStars: t6,
    fourStars: t3,
    pet: holy,
    pet2: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: crazyenvoy,
  },
  {
    name: 'The Last Avatar of God',
    slotOne: wbelesis,
    slotTwo: wbzero,
    slotThree: wbnelia,
    slotFour: wbgrandiel,
    oneStars: t3,
    twoStars: t3,
    threeStars: t3,
    fourStars: t3,
    pet: holy,
    pet2: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: crazyenvoy,
  },
  {
    name: 'Fire And Ice',
    slotOne: wbzero,
    slotTwo: wbelesis,
    slotThree: wbnelia,
    slotFour: wbgrandiel,
    oneStars: t3,
    twoStars: t3,
    threeStars: t3,
    fourStars: t3,
    pet: holy,
    pet2: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    fight: crazyenvoy,
  },
]

export const dChasm = [
  {
    name: 'Dark Poseidon',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Amy's Chasm",
    chasmImage: darkposeidon,
  },
  {
    name: 'Dark Hanout',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Arme's Chasm",
    chasmImage: darkhanout,
  },
  {
    name: 'Dark Rasel',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Ryan's Chasm",
    chasmImage: darkrasel,
  },
  {
    name: 'Dark Belial',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Ronan's Chasm",
    chasmImage: darkbelial,
  },
  {
    name: 'Dark Marjoram',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Lass's Chasm",
    chasmImage: darkmarjoram,
  },
  {
    name: 'Dark Captain Boar',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Mari's Chasm",
    chasmImage: darkcaptainboar,
  },
  {
    name: 'Dark Fennel',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Sieghart's Chasm",
    chasmImage: darkfennel,
  },
  {
    name: 'Dark Balzac',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Rufus's Chasm",
    chasmImage: darkbalzac,
  },
  {
    name: 'Dark Dr. Molly',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Lire's Chasm",
    chasmImage: darkdrmolly,
  },
  {
    name: 'Dark Agios',
    slotOne: wbronan,
    slotTwo: wbjin,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Jin's Chasm",
    chasmImage: darkagios,
  },
  {
    name: 'Dark Flaune',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Elesis's Chasm",
    chasmImage: darkflaune,
  },
  {
    name: 'Dark Charon',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Zero's Chasm",
    chasmImage: darkcharon,
  },
  {
    name: 'Dark Tacoel',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Rin's Chasm",
    chasmImage: darktacoel,
  },
  {
    name: 'Dark Nephilim',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Ley's Chasm",
    chasmImage: darknephilim,
  },
  {
    name: 'Dark Briel',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Lime's Chasm",
    chasmImage: darkbriel,
  },
  {
    name: 'Dark Dullahan',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Veigas's Chasm",
    chasmImage: darkdullahan,
  },
  {
    name: 'Dark Fermat',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Dio's Chasm",
    chasmImage: darkfermat,
  },
  {
    name: 'Dark Haggler',
    slotOne: wbronan,
    slotTwo: wbzero,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Nelia's Chasm",
    chasmImage: darkhaggler,
  },
  {
    name: 'Dark Altair',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Kanavan's Chasm",
    chasmImage: darkaltair,
  },
  {
    name: 'Dark Vega',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Edel's Chasm",
    chasmImage: darkvega,
  },
  {
    name: 'Dark BF',
    slotOne: wbronan,
    slotTwo: wbzero,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Serdin's Chasm",
    chasmImage: darkbf,
  },
  {
    name: 'Dark Favian',
    slotOne: wbronan,
    slotTwo: wblire,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Werner's Chasm",
    chasmImage: darkfavian,
  },
  {
    name: 'Dark Karp',
    slotOne: wbryan,
    slotTwo: wbio,
    slotThree: wbmari,
    slotFour: wbhwarin,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Asin's Chasm",
    chasmImage: darkkarp,
  },
  {
    name: 'Dark Kyle',
    slotOne: wbronan,
    slotTwo: wbzero,
    slotThree: wbio,
    slotFour: wbgrandiel,
    oneStars: t6,
    twoStars: t6,
    threeStars: t6,
    fourStars: t6,
    pet: holy,
    partySkillOne: stimulation,
    partySkillTwo: acceleration,
    partySkillThree: resurrect,
    specialHero: "Grandiel's Chasm",
    chasmImage: darkkyle,
  },
]
