export const grandChaseData = [
  {stage: '1-3', boss: 'Tank', mats: 'enchants', evos: 'none', sUnit: 'none'},
  {stage: '1-6', boss: 'Healer', mats: 'enchants', evos: 'none', sUnit: 'none'},
  {stage: '1-9', boss: 'Mage', mats: 'enchants', evos:'none', sUnit: 'none'},
  {stage: '2-3', boss: 'Mage', mats: 'enchants, BOV', evos: 'none', sUnit: 'none'},
  {stage: '2-6', boss: 'Mage', mats: 'enchants, BOV', evos: 'none', sUnit: 'none'},
  {stage: '2-9', boss: 'Ranger', mats: 'enchants, BOV', evos: 'none', sUnit: 'none'},
  {stage: '3-3', boss: 'Mage', mats: 'enchants, BOV', evos: 'healer', sUnit: 'none'},
  {stage: '3-6', boss: 'Mage', mats: 'enchants, BOV', evos: 'tank', sUnit: 'none'},
  {stage: '3-9', boss: 'Tank', mats: 'enchants, BOV', evos: 'assault', sUnit: 'none'},
  {stage: '4-3', boss: 'Tank', mats: 'enchants, BOV', evos: 'mage', sUnit: 'none'},
  {stage: '4-6', boss: 'Mage', mats: 'enchants, BOV', evos: 'ranger', sUnit: 'none'},
  {stage: '4-9', boss: 'Assault', mats: 'enchants, BOV', evos: 'healer', sUnit: 'none'},
  {stage: '5-3', boss: 'Assault', mats: 'enchants, BOV', evos: 'tank', sUnit: 'none'},
  {stage: '5-6', boss: 'Ranger', mats: 'enchants, BOV', evos: 'assault', sUnit: 'none'},
  {stage: '5-9', boss: 'Mage', mats: 'enchants, BOV', evos: 'mage', sUnit: 'none'},
  {stage: '6-3', boss: 'Mage', mats: 'enchants, BOV', evos: 'ranger', sUnit: 'none'},
  {stage: '6-6', boss: 'Ranger', mats: 'enchants, BOV', evos: 'tank', sUnit: 'Tank'},
  {stage: '6-9', boss: 'Mage', mats: 'enchants', evos: 'mage', sUnit: 'Mage'},
  {stage: '7-3', boss: 'Assault', mats: 'enchants', evos: 'ranger', sUnit: 'Ranger'},
  {stage: '7-6', boss: 'Mage', mats: 'enchants', evos: 'healer', sUnit: 'Healer'},
  {stage: '7-9', boss: 'Assault', mats: 'enchants', evos: 'assault', sUnit: 'Assault'},
  {stage: '8-3', boss: 'Assault', mats: 'enchants, BOV, runes', evos: 'healer', sUnit: 'none'},
  {stage: '8-6', boss: 'Ranger', mats: 'enchants, runes', evos: 'tank', sUnit: 'Tank'},
  {stage: '8-9', boss: 'Mage', mats: 'enchants, runes', evos: 'mage', sUnit: 'Mage'},
  {stage: '9-3', boss: 'Mage', mats: 'enchants, runes', evos: 'ranger', sUnit: 'Ranger'},
  {stage: '9-6', boss: 'Healer', mats: 'enchants, runes', evos: 'healer', sUnit: 'Healer'},
  {stage: '9-9', boss: 'Assault', mats: 'enchants, runes', evos: 'assault', sUnit: 'Assault'},
  {stage: '10-3', boss: 'Mage', mats: 'enchants, BOV, runes', evos: 'tank', sUnit: 'none'},
  {stage: '10-6', boss: 'Tank', mats: 'enchants, runes', evos: 'tank', sUnit: 'Tank'},
  {stage: '10-9', boss: 'Assault', mats: 'enchants, runes', evos: 'mage', sUnit: 'Mage'},
  {stage: '11-3', boss: 'Assault', mats: 'enchants, BOV, runes', evos: 'ranger', sUnit: 'none'},
  {stage: '11-6', boss: 'Tank', mats: 'enchants, runes', evos: 'ranger', sUnit: 'Ranger'},
  {stage: '11-9', boss: 'Assault', mats: 'enchants, runes', evos: 'healer', sUnit: 'Healer'},
  {stage: '12-3', boss: 'Mage', mats: 'enchants, runes', evos: 'assault', sUnit: 'Assault'},
  {stage: '12-6', boss:'Mage', mats: 'enchants, runes', evos: 'tank', sUnit: 'Tank'},
  {stage: '12-9', boss: 'Healer', mats: 'enchants, runes', evos: 'mage', sUnit: 'Mage'},
  {stage: '13-3', boss: 'Tank', mats: 'enchants, BOV, runes', evos: 'healer', sUnit: 'none'},
  {stage: '13-6', boss: 'Ranger', mats: 'enchants, runes', evos: 'ranger', sUnit: 'Ranger'},
  {stage: '13-9', boss: 'Assault', mats: 'enchants, runes', evos: 'healer', sUnit: 'Healer'},
  {stage: '14-3', boss: 'Mage', mats: 'enchants, BOV, runes, AOT', evos: 'mage', sUnit: 'none'},
  {stage: '14-6', boss: 'Healer', mats: 'enchants, runes, AOT', evos: 'assault', sUnit: 'Assault'},
  {stage: '14-9', boss: 'Mage', mats: 'enchants, runes, AOT', evos: 'tank', sUnit: 'Tank'},
  {stage: '15-3', boss: 'Tank', mats: 'enchants, runes, AOT', evos: 'mage', sUnit: 'Mage'},
  {stage: '15-6', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'ranger', sUnit: 'Ranger'},
  {stage: '15-9', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'healer', sUnit: 'Healer'},
  {stage: '16-3', boss: 'Assault', mats: 'enchants, BOV, runes, AOT', evos:'ranger', sUnit: 'none'},
  {stage: '16-6', boss: 'Ranger', mats: 'enchants, runes, AOT', evos: 'assault', sUnit: 'Assault'},
  {stage: '16-9', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'tank', sUnit: 'Tank'},
  {stage: '17-3', boss: 'Ranger', mats: 'enchants, BOV, runes, AOT', evos: 'assault', sUnit: 'none'},
  {stage: '17-6', boss: 'Healer', mats: 'enchants, runes, AOT', evos: 'mage', sUnit: 'Mage'},
  {stage: '17-9', boss: 'Mage', mats: 'enchants, runes, AOT', evos: 'ranger', sUnit: 'Ranger'},
  {stage: '18-3', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'healer', sUnit: 'Healer'},
  {stage: '18-6', boss: 'Mage', mats: 'enchants, runes, AOT', evos: 'assault', sUnit: 'Assault'},
  {stage: '18-9', boss: 'Healer', mats: 'enchants, runes, AOT', evos: 'tank', sUnit: 'Tank'},
  {stage: '19-3', boss: 'Tank', mats: 'enchants, BOV, runes, AOT', evos: 'mage', sUnit: 'none'},
  {stage: '19-6', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'mage', sUnit: 'Mage'},
  {stage: '19-9', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'ranger', sUnit: 'Ranger'},
  {stage: '20-3', boss: 'Assault', mats: 'enchants, BOV, runes, AOT', evos: 'tank', sUnit: 'none'},
  {stage: '20-6', boss: 'Healer', mats: 'enchants, runes, AOT', evos: 'healer', sUnit: 'Healer'},
  {stage: '20-9', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'assault', sUnit: 'Assault'},
  {stage: '21-3', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'tank', sUnit: 'Tank'},
  {stage: '21-6', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'mage', sUnit: 'Mage'},
  {stage: '21-9', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'ranger', sUnit: 'Ranger'},
  {stage: '22-3', boss: 'Mage', mats: 'enchants, BOV, runes, AOT', evos: 'assault', sUnit: 'none'},
  {stage: '22-6', boss: 'Ranger', mats: 'enchants, runes, AOT', evos: 'healer', sUnit: 'Healer'},
  {stage: '22-9', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'assault', sUnit: 'Assault'},
  {stage: 'Challenge 20-3', boss: 'Assault', mats: 'enchants, BOV, runes, AOT', evos: 'healer', sUnit: 'none'},
  {stage: 'Challenge 20-6', boss: 'Healer', mats: 'enchants, runes, AOT', evos: 'tank', sUnit: 'Tank'},
  {stage: 'Challenge 20-9', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'mage', sUnit: 'Mage'},
  {stage: 'Challenge 21-3', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'ranger', sUnit: 'Ranger'},
  {stage: 'Challenge 21-6', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'healer', sUnit: 'Healer'},
  {stage: 'Challenge 21-9', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'assault', sUnit: 'Assault'},
  {stage: 'Challenge 22-3', boss: 'Mage', mats: 'enchants, BOV, runes, AOT', evos: 'tank', sUnit: 'none'},
  {stage: 'Challenge 22-6', boss: 'Ranger', mats: 'enchants, runes, AOT', evos: 'tank', sUnit: 'Tank'},
  {stage: 'Challenge 22-9', boss: 'Assault', mats: 'enchants, runes, AOT', evos: 'mage', sUnit: 'Mage'}
]

export const evos = ['assault', 'tank', 'ranger', 'mage', 'healer'];
export const boss = ['Assault', 'Tank', 'Ranger', 'Mage', 'Healer'];
export const sUnit = ['Assault', 'Tank', 'Ranger', 'Mage', 'Healer'];
export const mats = ['BOV', 'enchants', 'runes', 'AOT']

export const heroes = [
  { id: "elesis", name: "Elesis", pic: "https://vignette.wikia.nocookie.net/grandchase/images/5/5f/Grand_Chase_for_kakao_Elesis_03.png/revision/latest?cb=20190907013422"},
  { id: "lire", name: "Lire", pic: "https://vignette.wikia.nocookie.net/grandchase/images/6/64/Grand_Chase_for_kakao_Lire_Eryuell_03.png/revision/latest?cb=20190902125444"},
  { id: "arme", name: "Arme", pic: "https://vignette.wikia.nocookie.net/grandchase/images/9/9b/Grand_Chase_for_kakao_Arme_03.png/revision/latest?cb=20190914124519"},
  { id: "lass", name: "Lass", pic: "https://vignette.wikia.nocookie.net/grandchase/images/3/3b/Grand_Chase_for_kakao_Lass_03.png/revision/latest?cb=20190319062942"},
  { id: "ryan", name: "Ryan", pic: "https://vignette.wikia.nocookie.net/grandchase/images/a/ac/Grand_Chase_for_kakao_Ryan_03.png/revision/latest?cb=20181211081423"},
  { id: "ronan", name: "Ronan", pic: "https://vignette.wikia.nocookie.net/grandchase/images/b/b6/Grand_Chase_for_kakao_Ronan_03.png/revision/latest?cb=20190914143527"},
  { id: "amy", name: "Amy", pic: "https://vignette.wikia.nocookie.net/grandchase/images/a/a6/Grand_Chase_for_kakao_Amy_03.png/revision/latest?cb=20181106062520"},
  { id: "jin", name: "Jin", pic: "https://vignette.wikia.nocookie.net/grandchase/images/f/f2/Grand_Chase_for_kakao_Jin_03.png/revision/latest?cb=20190718025204"},
  { id: "sieghart", name: "Sieghart", pic: "https://vignette.wikia.nocookie.net/grandchase/images/3/3e/Grand_Chase_for_kakao_Sieghart_03.png/revision/latest?cb=20190319063051"},
  { id: "mari", name: "Mari", pic: "https://vignette.wikia.nocookie.net/grandchase/images/a/a1/Grand_Chase_for_kakao_Mari_03.png/revision/latest?cb=20190914144435"},
  { id: "dio", name: "Dio", pic: "https://vignette.wikia.nocookie.net/grandchase/images/c/cb/Grand_Chase_for_kakao_Dio_03.png/revision/latest?cb=20190718025258"},
  { id: "zero", name: "Zero", pic: "https://vignette.wikia.nocookie.net/grandchase/images/9/98/Grand_Chase_for_kakao_Zero_03.png/revision/latest?cb=20190718025348"},
  { id: "ley", name: "Ley", pic: "https://vignette.wikia.nocookie.net/grandchase/images/4/4a/Grand_Chase_for_kakao_Ley_03.png/revision/latest?cb=20190409071206"},
  { id: "rufus", name: "Rufus", pic: "https://vignette.wikia.nocookie.net/grandchase/images/9/90/Grand_Chase_for_kakao_Rufus_03.png/revision/latest?cb=20181211081231"},
  { id: "rin", name: "Rin", pic: "https://vignette.wikia.nocookie.net/grandchase/images/0/00/Grand_Chase_for_kakao_Rin_03.png/revision/latest?cb=20190115024445"},
  { id: "asin", name: "Asin", pic: "https://vignette.wikia.nocookie.net/grandchase/images/2/27/Grand_Chase_for_kakao_Asin_03.png/revision/latest?cb=20190813110551"},
  { id: "lime", name: "Lime", pic: "https://vignette.wikia.nocookie.net/grandchase/images/9/94/Grand_Chase_for_kakao_Lime_03.png/revision/latest?cb=20190806100745"},
  { id: "edel", name: "Edel", pic: "https://vignette.wikia.nocookie.net/grandchase/images/e/ee/Grand_Chase_for_kakao_Edel_03.png/revision/latest?cb=20190718025428"},
  { id: "veigas", name: "Veigas", pic: "https://vignette.wikia.nocookie.net/grandchase/images/e/e9/Grand_Chase_for_kakao_Veigas_03.png/revision/latest?cb=20190707043615"},
  { id: "serdin", name: "Serdin", pic: "https://vignette.wikia.nocookie.net/grandchase/images/f/f0/Grand_Chase_for_kakao_Scarde_03.png/revision/latest?cb=20190416040937"},
  { id: "kanavan", name: "Kanavan", pic: "https://vignette.wikia.nocookie.net/grandchase/images/3/3c/Grand_Chase_for_kakao_Esnar_03.png/revision/latest?cb=20190521121207"},
  { id: "werner", name: "Werner", pic: "https://vignette.wikia.nocookie.net/grandchase/images/4/48/Grand_Chase_for_kakao_Werner_03.png/revision/latest?cb=20190718025510"},
  { id: "grandiel", name: "Grandiel", pic: "https://vignette.wikia.nocookie.net/grandchase/images/a/a8/Grand_Chase_for_kakao_Kassias_Grandiel_03.png/revision/latest?cb=20190718042310"},
  { id: "nelia", name: "Nelia", pic: "https://vignette.wikia.nocookie.net/grandchase/images/e/ed/Grand_Chase_for_kakao_Nellia_03.png/revision/latest?cb=20190910164429"},
  { id: "io", name: "Io", pic: "https://vignette.wikia.nocookie.net/grandchase/images/2/2a/Grand_Chase_for_kakao_Io_03.png/revision/latest/scale-to-width-down/620?cb=20200123225610"},
  { id: "gaian", name: "Dark Gaian", pic: "https://vignette.wikia.nocookie.net/grandchase/images/0/0f/Grand_Chase_for_kakao_Dark_Gaian_02.png/revision/latest?cb=20190823115505"},
  { id: "arsad", name: "Arsad", pic: "https://vignette.wikia.nocookie.net/grandchase/images/a/aa/Grand_Chase_for_kakao_Arsad_02.png/revision/latest?cb=20190823104047"}
]



export const heroBuilds= {
  elesis: {
    id:'elesis', 
    name: 'Elesis', 
    type: 'Assault',
    set: 'Power of Anger (blue)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/5/5f/Grand_Chase_for_kakao_Elesis_03.png/revision/latest?cb=20190907013422",
    limitBreak: 'S2 & Passive', 
    accessories: 'Solar Ring, Chasm Necklace, Earrings of Order', 
    traits:'Crit, CDR, SDI (4 points in each)', 
    sockets:'Physical Attack, Crit, SADI', 
    chaser05:'5/5 Elevated Power', 
    chaser10:'5/5 Divine Protection', 
    chaser15: '5/5 Fate', 
    chaser20:'5/5 Long Life', 
    chaser25:'3/3 Chaotic Judgement Part 1 & 2/2 Chaotic Judgement Part 2'
  },
  lire: {
    id:'lire', 
    name: 'Lire', 
    type: 'Ranger',
    set: 'Vows of Violence (green)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/6/64/Grand_Chase_for_kakao_Lire_Eryuell_03.png/revision/latest?cb=20190902125444",
    limitBreak: 'S2 & Passive', 
    accessories: 'Gale Ring, Lava Necklace, Earrings of Gust', 
    traits:'Crit, BASI, BADI (4 points in each)', 
    sockets:'Physical Attack, BASI, BADI', 
    chaser05:'5/5 Elevated Power',
    chaser10: '5/5 Invisible Hand',
    chaser15: '5/5 Fate',
    chaser20: '5/5 Impulse',
    chaser25: '3/3 Storm Arrow Part 1 & 2/2 Storm Arrow Part 2',
  },
  arme: {
    id:'arme', 
    name: 'Arme', 
    type: 'Mage',
    set: 'Dagger of Passion (orange)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/9/9b/Grand_Chase_for_kakao_Arme_03.png/revision/latest?cb=20190914124519",
    limitBreak: 'Passive & S2', 
    accessories: 'Solar Ring, Lava Necklace, Earrings of Order', 
    traits:'Crit, CDR, SDI (4 points in each)', 
    sockets:'Magic Attack, Crit/CDR, SADI', 
    chaser05:'?',
    chaser10: '?',
    chaser15: '?',
    chaser20: '?',
    chaser25: '3/3 Lightning Bolt Part 1 & 2/2 Lightning Bolt Part 2',
  },
  lass: {
    id:'lass', 
    name: 'Lass', 
    type: 'Assault',
    set: 'Dagger of Passion (orange)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/3/3b/Grand_Chase_for_kakao_Lass_03.png/revision/latest?cb=20190319062942",
    limitBreak: '?', 
    accessories: 'Solar Ring, Lava Necklace, Earrings of Order', 
    traits:'Crit, CDR, SDI (4 points in each)', 
    sockets:'Physical Attack, Crit, SADI', 
    chaser05:'?',
    chaser10: '?',
    chaser15: '?',
    chaser20: '?',
    chaser25: '3/3 Shadow Stranger Part 1 & 2/2 Shadow Stranger Part 2',
  },
  ryan: {
    id:'ryan', 
    name: 'Ryan', 
    type: 'Tank',
    set: 'Power of Anger (blue)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/a/ac/Grand_Chase_for_kakao_Ryan_03.png/revision/latest?cb=20181211081423",
    limitBreak: 'S1 & Passive', 
    accessories: 'Glacial Ring, Chasm Necklace, Earrings of Order', 
    traits:'BADR, SADR, HMRI (4 points in each)', 
    sockets:'Max Health, CDR, BADR', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  ronan: {
    id:'ronan', 
    name: 'Ronan', 
    type: 'Tank',
    set: 'Power of Anger (blue)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/b/b6/Grand_Chase_for_kakao_Ronan_03.png/revision/latest?cb=20190914143527",
    limitBreak: 'S2 & Passive', 
    accessories: 'Solar Ring, Chasm Necklace, Earrings of Order', 
    traits:'CDR, BADR, SADR (4 points in each)', 
    sockets:'Max Health, CDR, BADR', 
    chaser05:'?',
    chaser10: '?',
    chaser15: '?',
    chaser20: '?',
    chaser25: '3/3 Erudons Sword Part 1 & 2/2 Erudons Sword Part 2',
  },
  amy:{
    id:'amy', 
    name: 'Amy', 
    type: 'Healer',
    set: 'Vows of Violence (green)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/a/a6/Grand_Chase_for_kakao_Amy_03.png/revision/latest?cb=20181106062520",
    limitBreak: 'S1 & Passive', 
    accessories: 'Gale Ring, Chasm Necklace, Earrings of Order', 
    traits:'CDR, BASI, SADI (4 points in each)', 
    sockets:'Magic Attack, CDR/BASI, SADI', 
    chaser05:'?',
    chaser10: '?',
    chaser15: '?',
    chaser20: '?',
    chaser25: '3/3 Fan Service Part 1 & 2/2 Fan Service Part 2',
  },
  jin: {
    id:'jin', 
    name: 'Jin', 
    type: 'Tank',
    set: 'Dagger of Passion (orange)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/f/f2/Grand_Chase_for_kakao_Jin_03.png/revision/latest?cb=20190718025204",
    limitBreak: 'S1 & S2', 
    accessories: 'Solar Ring, Lava Necklace, Earrings of Gust', 
    traits:'Crit, BASI, SADI (4 points in each)', 
    sockets:'Max Health, CDR/Crit, SADI', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  sieghart: {
    id:'sieghart', 
    name: 'Sieghart', 
    type: 'Assault',
    set: 'Power of Anger (blue)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/3/3e/Grand_Chase_for_kakao_Sieghart_03.png/revision/latest?cb=20190319063051",
    limitBreak: 'Passive & S1', 
    accessories: 'Solar Ring, Chasm Necklace, Earrings of Order', 
    traits:'Crit, CDR, SADI (4 points in each)', 
    sockets:'Physical Attack, CDR, SADI', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  mari: {
    id:'mari', 
    name: 'Mari', 
    type: 'Mage',
    set: 'Vows of Violence (green)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/a/a1/Grand_Chase_for_kakao_Mari_03.png/revision/latest?cb=20190914144435",
    limitBreak: '?', 
    accessories: 'Gale Ring, Lava Necklace, Earrings of Gust', 
    traits:'Crit, BASI, BADI (4 points in each)', 
    sockets:'Magic Attack, BASI, SADI', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '3/3 Deadly Test Part 1 & 2/2 Deadly Test Part 2',
  },
  dio: {
    id:'dio', 
    name: 'Dio',
    type: 'Assault', 
    set: 'Power of Anger (blue)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/c/cb/Grand_Chase_for_kakao_Dio_03.png/revision/latest?cb=20190718025258",
    limitBreak: 'S1 & Passive', 
    accessories: 'Gale Ring, Chasm Necklace, Earrings of Order', 
    traits:'CDR, BASI, SADR (4 points in each)', 
    sockets:'Physical Attack, CDR, SADI', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  zero: {
    id:'zero', 
    name: 'Zero', 
    type: 'Tank',
    set: 'Dagger of Passion (orange)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/9/98/Grand_Chase_for_kakao_Zero_03.png/revision/latest?cb=20190718025348",
    limitBreak: 'S1 & Passive', 
    accessories: 'Solar Ring, Lava Necklace, Earrings of Order', 
    traits:'Crit, CDR, SADR (4 points in each)', 
    sockets:'Max Health, Crit, SADR', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  ley: {
    id:'ley', 
    name: 'Ley', 
    type: 'Mage',
    set: 'Vows of Violence (green)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/4/4a/Grand_Chase_for_kakao_Ley_03.png/revision/latest?cb=20190409071206",
    limitBreak: 'S2 & Passive', 
    accessories: 'Gale Ring, Chasm Necklace, Earrings of Gust', 
    traits:'Crit, BASI, BADI (4 points in each)', 
    sockets:'Magic Attack, BASI, BADI', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  rufus: {
    id:'rufus', 
    name: 'Rufus',
    type: 'Ranger', 
    set: 'Vows of Violence (green)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/9/90/Grand_Chase_for_kakao_Rufus_03.png/revision/latest?cb=20181211081231",
    limitBreak: 'S1 & S2', 
    accessories: 'Gale Ring, Lava Necklace, Earrings of Gust', 
    traits:'Crit, BASI, BADI (4 points in each)', 
    sockets:'Physical Attack, BASI/Crit, BADI', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  rin: {
    id:'rin', 
    name: 'Rin', 
    type: 'Healer',
    set: 'Power of Anger (blue)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/0/00/Grand_Chase_for_kakao_Rin_03.png/revision/latest?cb=20190115024445",
    limitBreak: 'S1 & S2', 
    accessories: 'Solar Ring, Chasm Necklace, Earrings of Order', 
    traits:'Crit, CDR, SADI (4 points in each)', 
    sockets:'Max Health, CDR/Crit, SADR/BADR', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '3/3 Chaotic Wind Part 1 & 2/2 Chaotic Wind Part 2',
  },
  asin: {
    id:'asin', 
    name: 'Asin', 
    type: 'Tank',
    set: 'Power of Anger (blue)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/2/27/Grand_Chase_for_kakao_Asin_03.png/revision/latest?cb=20190813110551",
    limitBreak: 'S1 & S2', 
    accessories: 'Gale Ring, Chasm Necklace, Earrings of Order', 
    traits:'Crit, CDR, SADI (4 points in each)', 
    sockets:'Max Health, CDR, BADR', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  lime: {
    id:'lime', 
    name: 'Lime', 
    type: 'Healer',
    set: 'Power of Anger (blue)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/9/94/Grand_Chase_for_kakao_Lime_03.png/revision/latest?cb=20190806100745",
    limitBreak: 'Passive & S2', 
    accessories: 'Solar Ring, Chasm Necklace, Earrings of Order', 
    traits:'CDR, BASI, SADI (4 points in each)', 
    sockets:'Max Health, CDR, SADR', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  edel: {
    id:'edel', 
    name: 'Edel', 
    type: 'Assault',
    set: 'Vows of Violence (green)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/e/ee/Grand_Chase_for_kakao_Edel_03.png/revision/latest?cb=20190718025428",
    limitBreak: 'S2 & Passive', 
    accessories: 'Gale Ring, Lava Necklace, Earrings of Gust', 
    traits:'CDR, BASI, BADI (4 points in each)', 
    sockets:'Physical Attack, BASI, BADI', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  veigas: {
    id:'veigas', 
    name: 'Veigas', 
    type: 'Mage',
    set: 'Dagger of Passion (orange)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/e/e9/Grand_Chase_for_kakao_Veigas_03.png/revision/latest?cb=20190707043615",
    limitBreak: 'S1 & Passive', 
    accessories: 'Solar Ring, Lava Necklace, Earrings of Order', 
    traits:'Crit, CDR, SADI (4 points in each)', 
    sockets:'Magic Attack, Crit/CDR, SADI', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  serdin: {
    id:'serdin', 
    name: 'Serdin', 
    type: 'Healer',
    set: 'Vows of Violence (green)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/f/f0/Grand_Chase_for_kakao_Scarde_03.png/revision/latest?cb=20190416040937",
    limitBreak: 'S1 & S2', 
    accessories: 'Gale Ring, Lava Necklace, Earrings of Gust', 
    traits:'CDR, BASI, BADI (4 points in each)', 
    sockets:'Magic Attack, CDR/BASI, SADR/BADI', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  kanavan: {
    id:'kanavan', 
    name: 'Kanavan', 
    type: 'Assault',
    set: 'Vows of Violence (green) or Dagger of Passion (orange)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/3/3c/Grand_Chase_for_kakao_Esnar_03.png/revision/latest?cb=20190521121207",
    limitBreak: 'S2 & S1', 
    accessories: 'Solar Ring, Lava Necklace, Earrings of Order', 
    traits:'Crit, BASI, SADI (4 points in each)', 
    sockets:'Physical Attack, Crit/BASI, SADI', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  werner: {
    id:'werner', 
    name: 'Werner', 
    type: 'Ranger',
    set: 'Spirit of Luck (pink)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/4/48/Grand_Chase_for_kakao_Werner_03.png/revision/latest?cb=20190718025510",
    limitBreak: 'Passive & S2', 
    accessories: 'Solar Ring, Chasm Necklace, Earrings of Order', 
    traits:'Crit, CDR, BADI (4 points in each)', 
    sockets:'Physical Attack, CDR/Crit, BADI/SADI', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  grandiel: {
    id:'grandiel', 
    name: 'Grandiel', 
    type: 'Healer',
    set: 'Power of Anger (blue)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/a/a8/Grand_Chase_for_kakao_Kassias_Grandiel_03.png/revision/latest?cb=20190718042310",
    limitBreak: 'S2 & S1', 
    accessories: 'Glacial Ring, Chasm Necklace, Earrings of Order', 
    traits:'CDR, SADR, BADR (4 points in each)', 
    sockets:'Magic Attack, CDR, SADR', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  nelia: {
    id:'nelia', 
    name: 'Nelia', 
    type: 'Mage',
    set: 'Dagger of Passion (orange)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/e/ed/Grand_Chase_for_kakao_Nellia_03.png/revision/latest?cb=20190910164429",
    limitBreak: 'S2 & Passive', 
    accessories: 'Solar Ring, Chasm Necklace, Earrings of Order', 
    traits:'Crit, CDR, SADI (4 points in each)', 
    sockets:'Magic Attack, CDR/Crit, SADI', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  io: {
    id:'io',
    name:'Io',
    type: 'Ranger',
    set: 'Power of Anger (blue) or Vows of Violence (green)',
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/2/2a/Grand_Chase_for_kakao_Io_03.png/revision/latest/scale-to-width-down/620?cb=20200123225610",
    limitBreak: 'S1 & S2', 
    accessories: 'Gale Ring, Chasm Necklace, Earrings of Gust', 
    traits:'BASI, BADI, CDR (4 points in each)', 
    sockets:'Physical Attack, BASI, BADI', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '3/3 Punisher Part 1 & 2/2 Punisher Part 2',
  },
  gaian: {
    id:'darkGaian', 
    name: 'Dark Gaian', 
    type: 'Mage',
    set: 'Dagger of Passion (orange)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/0/0f/Grand_Chase_for_kakao_Dark_Gaian_02.png/revision/latest?cb=20190823115505",
    limitBreak: 'N/A', 
    accessories: 'Sapling Ring, Lifeblood Necklace, Earrings of Order', 
    traits:'Crit, SADI, CSR (4 points in each)', 
    sockets:'Magic Attack, CSR, SADI', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
  arsad: {
    id:'arsad', 
    name: 'Arsad', 
    type: 'Tank',
    set: 'Power of Anger (blue)', 
    pic: "https://vignette.wikia.nocookie.net/grandchase/images/a/aa/Grand_Chase_for_kakao_Arsad_02.png/revision/latest?cb=20190823104047",
    limitBreak: 'N/A', 
    accessories: 'Glacial Ring, Chasm Necklace, Earrings of Order', 
    traits:'CDR, BADR, SADR (4 points in each)', 
    sockets:'Max Health, CDR, SADR', 
    chaser05:'',
    chaser10: '',
    chaser15: '',
    chaser20: '',
    chaser25: '',
  },
}